// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class PBDescriptorProto;
@class PBDescriptorProto_Builder;
@class PBDescriptorProto_ExtensionRange;
@class PBDescriptorProto_ExtensionRange_Builder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProto_Builder;
@class PBEnumOptions;
@class PBEnumOptions_Builder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProto_Builder;
@class PBEnumValueOptions;
@class PBEnumValueOptions_Builder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProto_Builder;
@class PBFieldOptions;
@class PBFieldOptions_Builder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProto_Builder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSet_Builder;
@class PBFileOptions;
@class PBFileOptions_Builder;
@class PBMessageOptions;
@class PBMessageOptions_Builder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProto_Builder;
@class PBMethodOptions;
@class PBMethodOptions_Builder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProto_Builder;
@class PBServiceOptions;
@class PBServiceOptions_Builder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfo_Builder;
@class PBSourceCodeInfo_Location;
@class PBSourceCodeInfo_Location_Builder;
@class PBUninterpretedOption;
@class PBUninterpretedOption_Builder;
@class PBUninterpretedOption_NamePart;
@class PBUninterpretedOption_NamePart_Builder;


#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


typedef enum {
  PBFieldDescriptorProto_TypeTypeDouble = 1,
  PBFieldDescriptorProto_TypeTypeFloat = 2,
  PBFieldDescriptorProto_TypeTypeInt64 = 3,
  PBFieldDescriptorProto_TypeTypeUint64 = 4,
  PBFieldDescriptorProto_TypeTypeInt32 = 5,
  PBFieldDescriptorProto_TypeTypeFixed64 = 6,
  PBFieldDescriptorProto_TypeTypeFixed32 = 7,
  PBFieldDescriptorProto_TypeTypeBool = 8,
  PBFieldDescriptorProto_TypeTypeString = 9,
  PBFieldDescriptorProto_TypeTypeGroup = 10,
  PBFieldDescriptorProto_TypeTypeMessage = 11,
  PBFieldDescriptorProto_TypeTypeBytes = 12,
  PBFieldDescriptorProto_TypeTypeUint32 = 13,
  PBFieldDescriptorProto_TypeTypeEnum = 14,
  PBFieldDescriptorProto_TypeTypeSfixed32 = 15,
  PBFieldDescriptorProto_TypeTypeSfixed64 = 16,
  PBFieldDescriptorProto_TypeTypeSint32 = 17,
  PBFieldDescriptorProto_TypeTypeSint64 = 18,
} PBFieldDescriptorProto_Type;

BOOL PBFieldDescriptorProto_TypeIsValidValue(PBFieldDescriptorProto_Type value);
NSString *PBFieldDescriptorProto_TypeToString(PBFieldDescriptorProto_Type value);


typedef enum {
  PBFieldDescriptorProto_LabelLabelOptional = 1,
  PBFieldDescriptorProto_LabelLabelRequired = 2,
  PBFieldDescriptorProto_LabelLabelRepeated = 3,
} PBFieldDescriptorProto_Label;

BOOL PBFieldDescriptorProto_LabelIsValidValue(PBFieldDescriptorProto_Label value);
NSString *PBFieldDescriptorProto_LabelToString(PBFieldDescriptorProto_Label value);


typedef enum {
  PBFileOptions_OptimizeModeSpeed = 1,
  PBFileOptions_OptimizeModeCodeSize = 2,
  PBFileOptions_OptimizeModeLiteRuntime = 3,
} PBFileOptions_OptimizeMode;

BOOL PBFileOptions_OptimizeModeIsValidValue(PBFileOptions_OptimizeMode value);
NSString *PBFileOptions_OptimizeModeToString(PBFileOptions_OptimizeMode value);


typedef enum {
  PBFieldOptions_CTypeString = 0,
  PBFieldOptions_CTypeCord = 1,
  PBFieldOptions_CTypeStringPiece = 2,
} PBFieldOptions_CType;

BOOL PBFieldOptions_CTypeIsValidValue(PBFieldOptions_CType value);
NSString *PBFieldOptions_CTypeToString(PBFieldOptions_CType value);


@interface PBDescriptorRoot : NSObject

+ (PBExtensionRegistry *)extensionRegistry;
+ (void)registerAllExtensions:(PBMutableExtensionRegistry *)registry;

@end


@interface PBFileDescriptorSet : PBGeneratedMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *file;
- (PBFileDescriptorProto *)fileAtIndex:(NSUInteger)index;
- (void)addFile:(PBFileDescriptorProto *)value;
- (void)addFileArray:(NSArray *)array;
- (void)setFileArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBFileDescriptorSet_Builder *)builder;
+ (PBFileDescriptorSet_Builder *)builder;
+ (PBFileDescriptorSet_Builder *)builderWithPrototype:(PBFileDescriptorSet *)prototype;
- (PBFileDescriptorSet_Builder *)toBuilder;

+ (PBFileDescriptorSet *)parseFromData:(NSData *)data;
+ (PBFileDescriptorSet *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileDescriptorSet *)parseFromInputStream:(NSInputStream *)input;
+ (PBFileDescriptorSet *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileDescriptorSet *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBFileDescriptorSet *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBFileDescriptorSet_Builder : PBGeneratedMessage_Builder

- (PBFileDescriptorSet_Builder *)clear;
- (PBFileDescriptorSet_Builder *)clone;

- (PBFileDescriptorSet *)build;
- (PBFileDescriptorSet *)buildPartial;

- (PBFileDescriptorSet_Builder *)mergeFrom:(PBFileDescriptorSet *)other;
- (PBFileDescriptorSet_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBFileDescriptorSet_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)file;
- (PBFileDescriptorProto *)fileAtIndex:(NSUInteger)index;
- (PBFileDescriptorSet_Builder *)addFile:(PBFileDescriptorProto *)value;
- (PBFileDescriptorSet_Builder *)setFileArray:(NSArray *)array;
- (PBFileDescriptorSet_Builder *)clearFile;

@end


@interface PBFileDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasName:1;
  BOOL _hasPackage:1;
  BOOL _hasOptions:1;
  BOOL _hasSourceCodeInfo:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic, strong) NSString *package;
- (void)clearPackage;
- (BOOL)hasPackage;

@property (nonatomic, strong) NSMutableArray *dependency;

@property (nonatomic, strong) NSMutableArray *messageType;
@property (nonatomic, strong) NSMutableArray *enumType;
@property (nonatomic, strong) NSMutableArray *service;
@property (nonatomic, strong) NSMutableArray *extension;
@property (nonatomic, strong) PBFileOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;

@property (nonatomic, strong) PBSourceCodeInfo *sourceCodeInfo;
- (void)clearSourceCodeInfo;
- (BOOL)hasSourceCodeInfo;

- (NSString *)dependencyAtIndex:(NSUInteger)index;
- (void)addDependency:(NSString *)value;
- (void)addDependencyArray:(NSArray *)array;
- (void)setDependencyArray:(NSArray *)array;
- (void)clearDependency;
- (PBDescriptorProto *)messageTypeAtIndex:(NSUInteger)index;
- (void)addMessageType:(PBDescriptorProto *)value;
- (void)addMessageTypeArray:(NSArray *)array;
- (void)setMessageTypeArray:(NSArray *)array;
- (PBEnumDescriptorProto *)enumTypeAtIndex:(NSUInteger)index;
- (void)addEnumType:(PBEnumDescriptorProto *)value;
- (void)addEnumTypeArray:(NSArray *)array;
- (void)setEnumTypeArray:(NSArray *)array;
- (PBServiceDescriptorProto *)serviceAtIndex:(NSUInteger)index;
- (void)addService:(PBServiceDescriptorProto *)value;
- (void)addServiceArray:(NSArray *)array;
- (void)setServiceArray:(NSArray *)array;
- (PBFieldDescriptorProto *)extensionAtIndex:(NSUInteger)index;
- (void)addExtension:(PBFieldDescriptorProto *)value;
- (void)addExtensionArray:(NSArray *)array;
- (void)setExtensionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBFileDescriptorProto_Builder *)builder;
+ (PBFileDescriptorProto_Builder *)builder;
+ (PBFileDescriptorProto_Builder *)builderWithPrototype:(PBFileDescriptorProto *)prototype;
- (PBFileDescriptorProto_Builder *)toBuilder;

+ (PBFileDescriptorProto *)parseFromData:(NSData *)data;
+ (PBFileDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBFileDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBFileDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBFileDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBFileDescriptorProto_Builder *)clear;
- (PBFileDescriptorProto_Builder *)clone;

- (PBFileDescriptorProto *)build;
- (PBFileDescriptorProto *)buildPartial;

- (PBFileDescriptorProto_Builder *)mergeFrom:(PBFileDescriptorProto *)other;
- (PBFileDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBFileDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBFileDescriptorProto_Builder *)setName:(NSString *)value;
- (PBFileDescriptorProto_Builder *)clearName;

- (BOOL)hasPackage;
- (NSString *)package;
- (PBFileDescriptorProto_Builder *)setPackage:(NSString *)value;
- (PBFileDescriptorProto_Builder *)clearPackage;

- (NSMutableArray *)dependency;
- (NSString *)dependencyAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addDependency:(NSString *)value;
- (PBFileDescriptorProto_Builder *)setDependencyArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)clearDependency;

- (NSMutableArray *)messageType;
- (PBDescriptorProto *)messageTypeAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addMessageType:(PBDescriptorProto *)value;
- (PBFileDescriptorProto_Builder *)setMessageTypeArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)clearMessageType;

- (NSMutableArray *)enumType;
- (PBEnumDescriptorProto *)enumTypeAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addEnumType:(PBEnumDescriptorProto *)value;
- (PBFileDescriptorProto_Builder *)setEnumTypeArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)clearEnumType;

- (NSMutableArray *)service;
- (PBServiceDescriptorProto *)serviceAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addService:(PBServiceDescriptorProto *)value;
- (PBFileDescriptorProto_Builder *)setServiceArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)clearService;

- (NSMutableArray *)extension;
- (PBFieldDescriptorProto *)extensionAtIndex:(NSUInteger)index;
- (PBFileDescriptorProto_Builder *)addExtension:(PBFieldDescriptorProto *)value;
- (PBFileDescriptorProto_Builder *)setExtensionArray:(NSArray *)array;
- (PBFileDescriptorProto_Builder *)clearExtension;

- (BOOL)hasOptions;
- (PBFileOptions *)options;
- (PBFileDescriptorProto_Builder *)setOptions:(PBFileOptions *)value;
- (PBFileDescriptorProto_Builder *)setOptionsBuilder:(PBFileOptions_Builder *)builderForValue;
- (PBFileDescriptorProto_Builder *)mergeOptions:(PBFileOptions *)value;
- (PBFileDescriptorProto_Builder *)clearOptions;

- (BOOL)hasSourceCodeInfo;
- (PBSourceCodeInfo *)sourceCodeInfo;
- (PBFileDescriptorProto_Builder *)setSourceCodeInfo:(PBSourceCodeInfo *)value;
- (PBFileDescriptorProto_Builder *)setSourceCodeInfoBuilder:(PBSourceCodeInfo_Builder *)builderForValue;
- (PBFileDescriptorProto_Builder *)mergeSourceCodeInfo:(PBSourceCodeInfo *)value;
- (PBFileDescriptorProto_Builder *)clearSourceCodeInfo;

@end


@interface PBDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasName:1;
  BOOL _hasOptions:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic, strong) NSMutableArray *field;
@property (nonatomic, strong) NSMutableArray *extension;
@property (nonatomic, strong) NSMutableArray *nestedType;
@property (nonatomic, strong) NSMutableArray *enumType;
@property (nonatomic, strong) NSMutableArray *extensionRange;
@property (nonatomic, strong) PBMessageOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;

- (PBFieldDescriptorProto *)fieldAtIndex:(NSUInteger)index;
- (void)addField:(PBFieldDescriptorProto *)value;
- (void)addFieldArray:(NSArray *)array;
- (void)setFieldArray:(NSArray *)array;
- (PBFieldDescriptorProto *)extensionAtIndex:(NSUInteger)index;
- (void)addExtension:(PBFieldDescriptorProto *)value;
- (void)addExtensionArray:(NSArray *)array;
- (void)setExtensionArray:(NSArray *)array;
- (PBDescriptorProto *)nestedTypeAtIndex:(NSUInteger)index;
- (void)addNestedType:(PBDescriptorProto *)value;
- (void)addNestedTypeArray:(NSArray *)array;
- (void)setNestedTypeArray:(NSArray *)array;
- (PBEnumDescriptorProto *)enumTypeAtIndex:(NSUInteger)index;
- (void)addEnumType:(PBEnumDescriptorProto *)value;
- (void)addEnumTypeArray:(NSArray *)array;
- (void)setEnumTypeArray:(NSArray *)array;
- (PBDescriptorProto_ExtensionRange *)extensionRangeAtIndex:(NSUInteger)index;
- (void)addExtensionRange:(PBDescriptorProto_ExtensionRange *)value;
- (void)addExtensionRangeArray:(NSArray *)array;
- (void)setExtensionRangeArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBDescriptorProto_Builder *)builder;
+ (PBDescriptorProto_Builder *)builder;
+ (PBDescriptorProto_Builder *)builderWithPrototype:(PBDescriptorProto *)prototype;
- (PBDescriptorProto_Builder *)toBuilder;

+ (PBDescriptorProto *)parseFromData:(NSData *)data;
+ (PBDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBDescriptorProto_ExtensionRange : PBGeneratedMessage {
@private
  BOOL _hasStart:1;
  BOOL _hasEnd:1;
}

@property (nonatomic) int32_t start;
- (void)clearStart;
- (BOOL)hasStart;

@property (nonatomic) int32_t end;
- (void)clearEnd;
- (BOOL)hasEnd;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBDescriptorProto_ExtensionRange_Builder *)builder;
+ (PBDescriptorProto_ExtensionRange_Builder *)builder;
+ (PBDescriptorProto_ExtensionRange_Builder *)builderWithPrototype:(PBDescriptorProto_ExtensionRange *)prototype;
- (PBDescriptorProto_ExtensionRange_Builder *)toBuilder;

+ (PBDescriptorProto_ExtensionRange *)parseFromData:(NSData *)data;
+ (PBDescriptorProto_ExtensionRange *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBDescriptorProto_ExtensionRange *)parseFromInputStream:(NSInputStream *)input;
+ (PBDescriptorProto_ExtensionRange *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBDescriptorProto_ExtensionRange *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBDescriptorProto_ExtensionRange *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBDescriptorProto_ExtensionRange_Builder : PBGeneratedMessage_Builder

- (PBDescriptorProto_ExtensionRange_Builder *)clear;
- (PBDescriptorProto_ExtensionRange_Builder *)clone;

- (PBDescriptorProto_ExtensionRange *)build;
- (PBDescriptorProto_ExtensionRange *)buildPartial;

- (PBDescriptorProto_ExtensionRange_Builder *)mergeFrom:(PBDescriptorProto_ExtensionRange *)other;
- (PBDescriptorProto_ExtensionRange_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBDescriptorProto_ExtensionRange_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasStart;
- (int32_t)start;
- (PBDescriptorProto_ExtensionRange_Builder *)setStart:(int32_t)value;
- (PBDescriptorProto_ExtensionRange_Builder *)clearStart;

- (BOOL)hasEnd;
- (int32_t)end;
- (PBDescriptorProto_ExtensionRange_Builder *)setEnd:(int32_t)value;
- (PBDescriptorProto_ExtensionRange_Builder *)clearEnd;

@end


@interface PBDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBDescriptorProto_Builder *)clear;
- (PBDescriptorProto_Builder *)clone;

- (PBDescriptorProto *)build;
- (PBDescriptorProto *)buildPartial;

- (PBDescriptorProto_Builder *)mergeFrom:(PBDescriptorProto *)other;
- (PBDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBDescriptorProto_Builder *)setName:(NSString *)value;
- (PBDescriptorProto_Builder *)clearName;

- (NSMutableArray *)field;
- (PBFieldDescriptorProto *)fieldAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addField:(PBFieldDescriptorProto *)value;
- (PBDescriptorProto_Builder *)setFieldArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)clearField;

- (NSMutableArray *)extension;
- (PBFieldDescriptorProto *)extensionAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addExtension:(PBFieldDescriptorProto *)value;
- (PBDescriptorProto_Builder *)setExtensionArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)clearExtension;

- (NSMutableArray *)nestedType;
- (PBDescriptorProto *)nestedTypeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addNestedType:(PBDescriptorProto *)value;
- (PBDescriptorProto_Builder *)setNestedTypeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)clearNestedType;

- (NSMutableArray *)enumType;
- (PBEnumDescriptorProto *)enumTypeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addEnumType:(PBEnumDescriptorProto *)value;
- (PBDescriptorProto_Builder *)setEnumTypeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)clearEnumType;

- (NSMutableArray *)extensionRange;
- (PBDescriptorProto_ExtensionRange *)extensionRangeAtIndex:(NSUInteger)index;
- (PBDescriptorProto_Builder *)addExtensionRange:(PBDescriptorProto_ExtensionRange *)value;
- (PBDescriptorProto_Builder *)setExtensionRangeArray:(NSArray *)array;
- (PBDescriptorProto_Builder *)clearExtensionRange;

- (BOOL)hasOptions;
- (PBMessageOptions *)options;
- (PBDescriptorProto_Builder *)setOptions:(PBMessageOptions *)value;
- (PBDescriptorProto_Builder *)setOptionsBuilder:(PBMessageOptions_Builder *)builderForValue;
- (PBDescriptorProto_Builder *)mergeOptions:(PBMessageOptions *)value;
- (PBDescriptorProto_Builder *)clearOptions;

@end


@interface PBFieldDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasNumber:1;
  BOOL _hasName:1;
  BOOL _hasTypeName:1;
  BOOL _hasExtendee:1;
  BOOL _hasDefaultValue:1;
  BOOL _hasOptions:1;
  BOOL _hasLabel:1;
  BOOL _hasType:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic) int32_t number;
- (void)clearNumber;
- (BOOL)hasNumber;

@property (nonatomic) PBFieldDescriptorProto_Label label;
- (void)clearLabel;
- (BOOL)hasLabel;

@property (nonatomic) PBFieldDescriptorProto_Type type;
- (void)clearType;
- (BOOL)hasType;

@property (nonatomic, strong) NSString *typeName;
- (void)clearTypeName;
- (BOOL)hasTypeName;

@property (nonatomic, strong) NSString *extendee;
- (void)clearExtendee;
- (BOOL)hasExtendee;

@property (nonatomic, strong) NSString *defaultValue;
- (void)clearDefaultValue;
- (BOOL)hasDefaultValue;

@property (nonatomic, strong) PBFieldOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBFieldDescriptorProto_Builder *)builder;
+ (PBFieldDescriptorProto_Builder *)builder;
+ (PBFieldDescriptorProto_Builder *)builderWithPrototype:(PBFieldDescriptorProto *)prototype;
- (PBFieldDescriptorProto_Builder *)toBuilder;

+ (PBFieldDescriptorProto *)parseFromData:(NSData *)data;
+ (PBFieldDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFieldDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBFieldDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFieldDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBFieldDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBFieldDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBFieldDescriptorProto_Builder *)clear;
- (PBFieldDescriptorProto_Builder *)clone;

- (PBFieldDescriptorProto *)build;
- (PBFieldDescriptorProto *)buildPartial;

- (PBFieldDescriptorProto_Builder *)mergeFrom:(PBFieldDescriptorProto *)other;
- (PBFieldDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBFieldDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBFieldDescriptorProto_Builder *)setName:(NSString *)value;
- (PBFieldDescriptorProto_Builder *)clearName;

- (BOOL)hasNumber;
- (int32_t)number;
- (PBFieldDescriptorProto_Builder *)setNumber:(int32_t)value;
- (PBFieldDescriptorProto_Builder *)clearNumber;

- (BOOL)hasLabel;
- (PBFieldDescriptorProto_Label)label;
- (PBFieldDescriptorProto_Builder *)setLabel:(PBFieldDescriptorProto_Label)value;
- (PBFieldDescriptorProto_Builder *)clearLabel;

- (BOOL)hasType;
- (PBFieldDescriptorProto_Type)type;
- (PBFieldDescriptorProto_Builder *)setType:(PBFieldDescriptorProto_Type)value;
- (PBFieldDescriptorProto_Builder *)clearType;

- (BOOL)hasTypeName;
- (NSString *)typeName;
- (PBFieldDescriptorProto_Builder *)setTypeName:(NSString *)value;
- (PBFieldDescriptorProto_Builder *)clearTypeName;

- (BOOL)hasExtendee;
- (NSString *)extendee;
- (PBFieldDescriptorProto_Builder *)setExtendee:(NSString *)value;
- (PBFieldDescriptorProto_Builder *)clearExtendee;

- (BOOL)hasDefaultValue;
- (NSString *)defaultValue;
- (PBFieldDescriptorProto_Builder *)setDefaultValue:(NSString *)value;
- (PBFieldDescriptorProto_Builder *)clearDefaultValue;

- (BOOL)hasOptions;
- (PBFieldOptions *)options;
- (PBFieldDescriptorProto_Builder *)setOptions:(PBFieldOptions *)value;
- (PBFieldDescriptorProto_Builder *)setOptionsBuilder:(PBFieldOptions_Builder *)builderForValue;
- (PBFieldDescriptorProto_Builder *)mergeOptions:(PBFieldOptions *)value;
- (PBFieldDescriptorProto_Builder *)clearOptions;

@end


@interface PBEnumDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasName:1;
  BOOL _hasOptions:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic, strong) NSMutableArray *value;
@property (nonatomic, strong) PBEnumOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;

- (PBEnumValueDescriptorProto *)valueAtIndex:(NSUInteger)index;
- (void)addValue:(PBEnumValueDescriptorProto *)value;
- (void)addValueArray:(NSArray *)array;
- (void)setValueArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBEnumDescriptorProto_Builder *)builder;
+ (PBEnumDescriptorProto_Builder *)builder;
+ (PBEnumDescriptorProto_Builder *)builderWithPrototype:(PBEnumDescriptorProto *)prototype;
- (PBEnumDescriptorProto_Builder *)toBuilder;

+ (PBEnumDescriptorProto *)parseFromData:(NSData *)data;
+ (PBEnumDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBEnumDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBEnumDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBEnumDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBEnumDescriptorProto_Builder *)clear;
- (PBEnumDescriptorProto_Builder *)clone;

- (PBEnumDescriptorProto *)build;
- (PBEnumDescriptorProto *)buildPartial;

- (PBEnumDescriptorProto_Builder *)mergeFrom:(PBEnumDescriptorProto *)other;
- (PBEnumDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBEnumDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBEnumDescriptorProto_Builder *)setName:(NSString *)value;
- (PBEnumDescriptorProto_Builder *)clearName;

- (NSMutableArray *)value;
- (PBEnumValueDescriptorProto *)valueAtIndex:(NSUInteger)index;
- (PBEnumDescriptorProto_Builder *)addValue:(PBEnumValueDescriptorProto *)value;
- (PBEnumDescriptorProto_Builder *)setValueArray:(NSArray *)array;
- (PBEnumDescriptorProto_Builder *)clearValue;

- (BOOL)hasOptions;
- (PBEnumOptions *)options;
- (PBEnumDescriptorProto_Builder *)setOptions:(PBEnumOptions *)value;
- (PBEnumDescriptorProto_Builder *)setOptionsBuilder:(PBEnumOptions_Builder *)builderForValue;
- (PBEnumDescriptorProto_Builder *)mergeOptions:(PBEnumOptions *)value;
- (PBEnumDescriptorProto_Builder *)clearOptions;

@end


@interface PBEnumValueDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasNumber:1;
  BOOL _hasName:1;
  BOOL _hasOptions:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic) int32_t number;
- (void)clearNumber;
- (BOOL)hasNumber;

@property (nonatomic, strong) PBEnumValueOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBEnumValueDescriptorProto_Builder *)builder;
+ (PBEnumValueDescriptorProto_Builder *)builder;
+ (PBEnumValueDescriptorProto_Builder *)builderWithPrototype:(PBEnumValueDescriptorProto *)prototype;
- (PBEnumValueDescriptorProto_Builder *)toBuilder;

+ (PBEnumValueDescriptorProto *)parseFromData:(NSData *)data;
+ (PBEnumValueDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumValueDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBEnumValueDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumValueDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBEnumValueDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBEnumValueDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBEnumValueDescriptorProto_Builder *)clear;
- (PBEnumValueDescriptorProto_Builder *)clone;

- (PBEnumValueDescriptorProto *)build;
- (PBEnumValueDescriptorProto *)buildPartial;

- (PBEnumValueDescriptorProto_Builder *)mergeFrom:(PBEnumValueDescriptorProto *)other;
- (PBEnumValueDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBEnumValueDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBEnumValueDescriptorProto_Builder *)setName:(NSString *)value;
- (PBEnumValueDescriptorProto_Builder *)clearName;

- (BOOL)hasNumber;
- (int32_t)number;
- (PBEnumValueDescriptorProto_Builder *)setNumber:(int32_t)value;
- (PBEnumValueDescriptorProto_Builder *)clearNumber;

- (BOOL)hasOptions;
- (PBEnumValueOptions *)options;
- (PBEnumValueDescriptorProto_Builder *)setOptions:(PBEnumValueOptions *)value;
- (PBEnumValueDescriptorProto_Builder *)setOptionsBuilder:(PBEnumValueOptions_Builder *)builderForValue;
- (PBEnumValueDescriptorProto_Builder *)mergeOptions:(PBEnumValueOptions *)value;
- (PBEnumValueDescriptorProto_Builder *)clearOptions;

@end


@interface PBServiceDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasName:1;
  BOOL _hasOptions:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic, strong) NSMutableArray *method;
@property (nonatomic, strong) PBServiceOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;

- (PBMethodDescriptorProto *)methodAtIndex:(NSUInteger)index;
- (void)addMethod:(PBMethodDescriptorProto *)value;
- (void)addMethodArray:(NSArray *)array;
- (void)setMethodArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBServiceDescriptorProto_Builder *)builder;
+ (PBServiceDescriptorProto_Builder *)builder;
+ (PBServiceDescriptorProto_Builder *)builderWithPrototype:(PBServiceDescriptorProto *)prototype;
- (PBServiceDescriptorProto_Builder *)toBuilder;

+ (PBServiceDescriptorProto *)parseFromData:(NSData *)data;
+ (PBServiceDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBServiceDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBServiceDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBServiceDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBServiceDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBServiceDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBServiceDescriptorProto_Builder *)clear;
- (PBServiceDescriptorProto_Builder *)clone;

- (PBServiceDescriptorProto *)build;
- (PBServiceDescriptorProto *)buildPartial;

- (PBServiceDescriptorProto_Builder *)mergeFrom:(PBServiceDescriptorProto *)other;
- (PBServiceDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBServiceDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBServiceDescriptorProto_Builder *)setName:(NSString *)value;
- (PBServiceDescriptorProto_Builder *)clearName;

- (NSMutableArray *)method;
- (PBMethodDescriptorProto *)methodAtIndex:(NSUInteger)index;
- (PBServiceDescriptorProto_Builder *)addMethod:(PBMethodDescriptorProto *)value;
- (PBServiceDescriptorProto_Builder *)setMethodArray:(NSArray *)array;
- (PBServiceDescriptorProto_Builder *)clearMethod;

- (BOOL)hasOptions;
- (PBServiceOptions *)options;
- (PBServiceDescriptorProto_Builder *)setOptions:(PBServiceOptions *)value;
- (PBServiceDescriptorProto_Builder *)setOptionsBuilder:(PBServiceOptions_Builder *)builderForValue;
- (PBServiceDescriptorProto_Builder *)mergeOptions:(PBServiceOptions *)value;
- (PBServiceDescriptorProto_Builder *)clearOptions;

@end


@interface PBMethodDescriptorProto : PBGeneratedMessage {
@private
  BOOL _hasName:1;
  BOOL _hasInputType:1;
  BOOL _hasOutputType:1;
  BOOL _hasOptions:1;
}

@property (nonatomic, strong) NSString *name;
- (void)clearName;
- (BOOL)hasName;

@property (nonatomic, strong) NSString *inputType;
- (void)clearInputType;
- (BOOL)hasInputType;

@property (nonatomic, strong) NSString *outputType;
- (void)clearOutputType;
- (BOOL)hasOutputType;

@property (nonatomic, strong) PBMethodOptions *options;
- (void)clearOptions;
- (BOOL)hasOptions;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBMethodDescriptorProto_Builder *)builder;
+ (PBMethodDescriptorProto_Builder *)builder;
+ (PBMethodDescriptorProto_Builder *)builderWithPrototype:(PBMethodDescriptorProto *)prototype;
- (PBMethodDescriptorProto_Builder *)toBuilder;

+ (PBMethodDescriptorProto *)parseFromData:(NSData *)data;
+ (PBMethodDescriptorProto *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMethodDescriptorProto *)parseFromInputStream:(NSInputStream *)input;
+ (PBMethodDescriptorProto *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMethodDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBMethodDescriptorProto *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBMethodDescriptorProto_Builder : PBGeneratedMessage_Builder

- (PBMethodDescriptorProto_Builder *)clear;
- (PBMethodDescriptorProto_Builder *)clone;

- (PBMethodDescriptorProto *)build;
- (PBMethodDescriptorProto *)buildPartial;

- (PBMethodDescriptorProto_Builder *)mergeFrom:(PBMethodDescriptorProto *)other;
- (PBMethodDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBMethodDescriptorProto_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasName;
- (NSString *)name;
- (PBMethodDescriptorProto_Builder *)setName:(NSString *)value;
- (PBMethodDescriptorProto_Builder *)clearName;

- (BOOL)hasInputType;
- (NSString *)inputType;
- (PBMethodDescriptorProto_Builder *)setInputType:(NSString *)value;
- (PBMethodDescriptorProto_Builder *)clearInputType;

- (BOOL)hasOutputType;
- (NSString *)outputType;
- (PBMethodDescriptorProto_Builder *)setOutputType:(NSString *)value;
- (PBMethodDescriptorProto_Builder *)clearOutputType;

- (BOOL)hasOptions;
- (PBMethodOptions *)options;
- (PBMethodDescriptorProto_Builder *)setOptions:(PBMethodOptions *)value;
- (PBMethodDescriptorProto_Builder *)setOptionsBuilder:(PBMethodOptions_Builder *)builderForValue;
- (PBMethodDescriptorProto_Builder *)mergeOptions:(PBMethodOptions *)value;
- (PBMethodDescriptorProto_Builder *)clearOptions;

@end


@interface PBFileOptions : PBExtendableMessage {
@private
  BOOL _hasJavaMultipleFiles:1;
  BOOL _hasJavaGenerateEqualsAndHash:1;
  BOOL _hasCcGenericServices:1;
  BOOL _hasJavaGenericServices:1;
  BOOL _hasPyGenericServices:1;
  BOOL _hasJavaPackage:1;
  BOOL _hasJavaOuterClassname:1;
  BOOL _hasOptimizeFor:1;
}

@property (nonatomic, strong) NSString *javaPackage;
- (void)clearJavaPackage;
- (BOOL)hasJavaPackage;

@property (nonatomic, strong) NSString *javaOuterClassname;
- (void)clearJavaOuterClassname;
- (BOOL)hasJavaOuterClassname;

@property (nonatomic) BOOL javaMultipleFiles;
- (void)clearJavaMultipleFiles;
- (BOOL)hasJavaMultipleFiles;

@property (nonatomic) BOOL javaGenerateEqualsAndHash;
- (void)clearJavaGenerateEqualsAndHash;
- (BOOL)hasJavaGenerateEqualsAndHash;

@property (nonatomic) PBFileOptions_OptimizeMode optimizeFor;
- (void)clearOptimizeFor;
- (BOOL)hasOptimizeFor;

@property (nonatomic) BOOL ccGenericServices;
- (void)clearCcGenericServices;
- (BOOL)hasCcGenericServices;

@property (nonatomic) BOOL javaGenericServices;
- (void)clearJavaGenericServices;
- (BOOL)hasJavaGenericServices;

@property (nonatomic) BOOL pyGenericServices;
- (void)clearPyGenericServices;
- (BOOL)hasPyGenericServices;

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBFileOptions_Builder *)builder;
+ (PBFileOptions_Builder *)builder;
+ (PBFileOptions_Builder *)builderWithPrototype:(PBFileOptions *)prototype;
- (PBFileOptions_Builder *)toBuilder;

+ (PBFileOptions *)parseFromData:(NSData *)data;
+ (PBFileOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBFileOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFileOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBFileOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBFileOptions_Builder : PBExtendableMessage_Builder

- (PBFileOptions_Builder *)clear;
- (PBFileOptions_Builder *)clone;

- (PBFileOptions *)build;
- (PBFileOptions *)buildPartial;

- (PBFileOptions_Builder *)mergeFrom:(PBFileOptions *)other;
- (PBFileOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBFileOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasJavaPackage;
- (NSString *)javaPackage;
- (PBFileOptions_Builder *)setJavaPackage:(NSString *)value;
- (PBFileOptions_Builder *)clearJavaPackage;

- (BOOL)hasJavaOuterClassname;
- (NSString *)javaOuterClassname;
- (PBFileOptions_Builder *)setJavaOuterClassname:(NSString *)value;
- (PBFileOptions_Builder *)clearJavaOuterClassname;

- (BOOL)hasJavaMultipleFiles;
- (BOOL)javaMultipleFiles;
- (PBFileOptions_Builder *)setJavaMultipleFiles:(BOOL)value;
- (PBFileOptions_Builder *)clearJavaMultipleFiles;

- (BOOL)hasJavaGenerateEqualsAndHash;
- (BOOL)javaGenerateEqualsAndHash;
- (PBFileOptions_Builder *)setJavaGenerateEqualsAndHash:(BOOL)value;
- (PBFileOptions_Builder *)clearJavaGenerateEqualsAndHash;

- (BOOL)hasOptimizeFor;
- (PBFileOptions_OptimizeMode)optimizeFor;
- (PBFileOptions_Builder *)setOptimizeFor:(PBFileOptions_OptimizeMode)value;
- (PBFileOptions_Builder *)clearOptimizeFor;

- (BOOL)hasCcGenericServices;
- (BOOL)ccGenericServices;
- (PBFileOptions_Builder *)setCcGenericServices:(BOOL)value;
- (PBFileOptions_Builder *)clearCcGenericServices;

- (BOOL)hasJavaGenericServices;
- (BOOL)javaGenericServices;
- (PBFileOptions_Builder *)setJavaGenericServices:(BOOL)value;
- (PBFileOptions_Builder *)clearJavaGenericServices;

- (BOOL)hasPyGenericServices;
- (BOOL)pyGenericServices;
- (PBFileOptions_Builder *)setPyGenericServices:(BOOL)value;
- (PBFileOptions_Builder *)clearPyGenericServices;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBFileOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBFileOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBFileOptions_Builder *)clearUninterpretedOption;

@end


@interface PBMessageOptions : PBExtendableMessage {
@private
  BOOL _hasMessageSetWireFormat:1;
  BOOL _hasNoStandardDescriptorAccessor:1;
}

@property (nonatomic) BOOL messageSetWireFormat;
- (void)clearMessageSetWireFormat;
- (BOOL)hasMessageSetWireFormat;

@property (nonatomic) BOOL noStandardDescriptorAccessor;
- (void)clearNoStandardDescriptorAccessor;
- (BOOL)hasNoStandardDescriptorAccessor;

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBMessageOptions_Builder *)builder;
+ (PBMessageOptions_Builder *)builder;
+ (PBMessageOptions_Builder *)builderWithPrototype:(PBMessageOptions *)prototype;
- (PBMessageOptions_Builder *)toBuilder;

+ (PBMessageOptions *)parseFromData:(NSData *)data;
+ (PBMessageOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMessageOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBMessageOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMessageOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBMessageOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBMessageOptions_Builder : PBExtendableMessage_Builder

- (PBMessageOptions_Builder *)clear;
- (PBMessageOptions_Builder *)clone;

- (PBMessageOptions *)build;
- (PBMessageOptions *)buildPartial;

- (PBMessageOptions_Builder *)mergeFrom:(PBMessageOptions *)other;
- (PBMessageOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBMessageOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasMessageSetWireFormat;
- (BOOL)messageSetWireFormat;
- (PBMessageOptions_Builder *)setMessageSetWireFormat:(BOOL)value;
- (PBMessageOptions_Builder *)clearMessageSetWireFormat;

- (BOOL)hasNoStandardDescriptorAccessor;
- (BOOL)noStandardDescriptorAccessor;
- (PBMessageOptions_Builder *)setNoStandardDescriptorAccessor:(BOOL)value;
- (PBMessageOptions_Builder *)clearNoStandardDescriptorAccessor;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBMessageOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBMessageOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBMessageOptions_Builder *)clearUninterpretedOption;

@end


@interface PBFieldOptions : PBExtendableMessage {
@private
  BOOL _hasPacked:1;
  BOOL _hasDeprecated:1;
  BOOL _hasExperimentalMapKey:1;
  BOOL _hasCtype:1;
}

@property (nonatomic) PBFieldOptions_CType ctype;
- (void)clearCtype;
- (BOOL)hasCtype;

@property (nonatomic) BOOL packed;
- (void)clearPacked;
- (BOOL)hasPacked;

@property (nonatomic) BOOL deprecated;
- (void)clearDeprecated;
- (BOOL)hasDeprecated;

@property (nonatomic, strong) NSString *experimentalMapKey;
- (void)clearExperimentalMapKey;
- (BOOL)hasExperimentalMapKey;

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBFieldOptions_Builder *)builder;
+ (PBFieldOptions_Builder *)builder;
+ (PBFieldOptions_Builder *)builderWithPrototype:(PBFieldOptions *)prototype;
- (PBFieldOptions_Builder *)toBuilder;

+ (PBFieldOptions *)parseFromData:(NSData *)data;
+ (PBFieldOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFieldOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBFieldOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBFieldOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBFieldOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBFieldOptions_Builder : PBExtendableMessage_Builder

- (PBFieldOptions_Builder *)clear;
- (PBFieldOptions_Builder *)clone;

- (PBFieldOptions *)build;
- (PBFieldOptions *)buildPartial;

- (PBFieldOptions_Builder *)mergeFrom:(PBFieldOptions *)other;
- (PBFieldOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBFieldOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasCtype;
- (PBFieldOptions_CType)ctype;
- (PBFieldOptions_Builder *)setCtype:(PBFieldOptions_CType)value;
- (PBFieldOptions_Builder *)clearCtype;

- (BOOL)hasPacked;
- (BOOL)packed;
- (PBFieldOptions_Builder *)setPacked:(BOOL)value;
- (PBFieldOptions_Builder *)clearPacked;

- (BOOL)hasDeprecated;
- (BOOL)deprecated;
- (PBFieldOptions_Builder *)setDeprecated:(BOOL)value;
- (PBFieldOptions_Builder *)clearDeprecated;

- (BOOL)hasExperimentalMapKey;
- (NSString *)experimentalMapKey;
- (PBFieldOptions_Builder *)setExperimentalMapKey:(NSString *)value;
- (PBFieldOptions_Builder *)clearExperimentalMapKey;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBFieldOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBFieldOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBFieldOptions_Builder *)clearUninterpretedOption;

@end


@interface PBEnumOptions : PBExtendableMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBEnumOptions_Builder *)builder;
+ (PBEnumOptions_Builder *)builder;
+ (PBEnumOptions_Builder *)builderWithPrototype:(PBEnumOptions *)prototype;
- (PBEnumOptions_Builder *)toBuilder;

+ (PBEnumOptions *)parseFromData:(NSData *)data;
+ (PBEnumOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBEnumOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBEnumOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBEnumOptions_Builder : PBExtendableMessage_Builder

- (PBEnumOptions_Builder *)clear;
- (PBEnumOptions_Builder *)clone;

- (PBEnumOptions *)build;
- (PBEnumOptions *)buildPartial;

- (PBEnumOptions_Builder *)mergeFrom:(PBEnumOptions *)other;
- (PBEnumOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBEnumOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBEnumOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBEnumOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBEnumOptions_Builder *)clearUninterpretedOption;

@end


@interface PBEnumValueOptions : PBExtendableMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBEnumValueOptions_Builder *)builder;
+ (PBEnumValueOptions_Builder *)builder;
+ (PBEnumValueOptions_Builder *)builderWithPrototype:(PBEnumValueOptions *)prototype;
- (PBEnumValueOptions_Builder *)toBuilder;

+ (PBEnumValueOptions *)parseFromData:(NSData *)data;
+ (PBEnumValueOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumValueOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBEnumValueOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBEnumValueOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBEnumValueOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBEnumValueOptions_Builder : PBExtendableMessage_Builder

- (PBEnumValueOptions_Builder *)clear;
- (PBEnumValueOptions_Builder *)clone;

- (PBEnumValueOptions *)build;
- (PBEnumValueOptions *)buildPartial;

- (PBEnumValueOptions_Builder *)mergeFrom:(PBEnumValueOptions *)other;
- (PBEnumValueOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBEnumValueOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBEnumValueOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBEnumValueOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBEnumValueOptions_Builder *)clearUninterpretedOption;

@end


@interface PBServiceOptions : PBExtendableMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBServiceOptions_Builder *)builder;
+ (PBServiceOptions_Builder *)builder;
+ (PBServiceOptions_Builder *)builderWithPrototype:(PBServiceOptions *)prototype;
- (PBServiceOptions_Builder *)toBuilder;

+ (PBServiceOptions *)parseFromData:(NSData *)data;
+ (PBServiceOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBServiceOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBServiceOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBServiceOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBServiceOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBServiceOptions_Builder : PBExtendableMessage_Builder

- (PBServiceOptions_Builder *)clear;
- (PBServiceOptions_Builder *)clone;

- (PBServiceOptions *)build;
- (PBServiceOptions *)buildPartial;

- (PBServiceOptions_Builder *)mergeFrom:(PBServiceOptions *)other;
- (PBServiceOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBServiceOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBServiceOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBServiceOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBServiceOptions_Builder *)clearUninterpretedOption;

@end


@interface PBMethodOptions : PBExtendableMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (void)addUninterpretedOption:(PBUninterpretedOption *)value;
- (void)addUninterpretedOptionArray:(NSArray *)array;
- (void)setUninterpretedOptionArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBMethodOptions_Builder *)builder;
+ (PBMethodOptions_Builder *)builder;
+ (PBMethodOptions_Builder *)builderWithPrototype:(PBMethodOptions *)prototype;
- (PBMethodOptions_Builder *)toBuilder;

+ (PBMethodOptions *)parseFromData:(NSData *)data;
+ (PBMethodOptions *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMethodOptions *)parseFromInputStream:(NSInputStream *)input;
+ (PBMethodOptions *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBMethodOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBMethodOptions *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBMethodOptions_Builder : PBExtendableMessage_Builder

- (PBMethodOptions_Builder *)clear;
- (PBMethodOptions_Builder *)clone;

- (PBMethodOptions *)build;
- (PBMethodOptions *)buildPartial;

- (PBMethodOptions_Builder *)mergeFrom:(PBMethodOptions *)other;
- (PBMethodOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBMethodOptions_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)uninterpretedOption;
- (PBUninterpretedOption *)uninterpretedOptionAtIndex:(NSUInteger)index;
- (PBMethodOptions_Builder *)addUninterpretedOption:(PBUninterpretedOption *)value;
- (PBMethodOptions_Builder *)setUninterpretedOptionArray:(NSArray *)array;
- (PBMethodOptions_Builder *)clearUninterpretedOption;

@end


@interface PBUninterpretedOption : PBGeneratedMessage {
@private
  BOOL _hasDoubleValue:1;
  BOOL _hasNegativeIntValue:1;
  BOOL _hasPositiveIntValue:1;
  BOOL _hasIdentifierValue:1;
  BOOL _hasAggregateValue:1;
  BOOL _hasStringValue:1;
}

@property (nonatomic, strong) NSMutableArray *name;
@property (nonatomic, strong) NSString *identifierValue;
- (void)clearIdentifierValue;
- (BOOL)hasIdentifierValue;

@property (nonatomic) uint64_t positiveIntValue;
- (void)clearPositiveIntValue;
- (BOOL)hasPositiveIntValue;

@property (nonatomic) int64_t negativeIntValue;
- (void)clearNegativeIntValue;
- (BOOL)hasNegativeIntValue;

@property (nonatomic) Float64 doubleValue;
- (void)clearDoubleValue;
- (BOOL)hasDoubleValue;

@property (nonatomic, strong) NSData *stringValue;
- (void)clearStringValue;
- (BOOL)hasStringValue;

@property (nonatomic, strong) NSString *aggregateValue;
- (void)clearAggregateValue;
- (BOOL)hasAggregateValue;

- (PBUninterpretedOption_NamePart *)nameAtIndex:(NSUInteger)index;
- (void)addName:(PBUninterpretedOption_NamePart *)value;
- (void)addNameArray:(NSArray *)array;
- (void)setNameArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBUninterpretedOption_Builder *)builder;
+ (PBUninterpretedOption_Builder *)builder;
+ (PBUninterpretedOption_Builder *)builderWithPrototype:(PBUninterpretedOption *)prototype;
- (PBUninterpretedOption_Builder *)toBuilder;

+ (PBUninterpretedOption *)parseFromData:(NSData *)data;
+ (PBUninterpretedOption *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBUninterpretedOption *)parseFromInputStream:(NSInputStream *)input;
+ (PBUninterpretedOption *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBUninterpretedOption *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBUninterpretedOption *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBUninterpretedOption_NamePart : PBGeneratedMessage {
@private
  BOOL _hasIsExtension:1;
  BOOL _hasNamePart:1;
}

@property (nonatomic, strong) NSString *namePart;
- (void)clearNamePart;
- (BOOL)hasNamePart;

@property (nonatomic) BOOL isExtension;
- (void)clearIsExtension;
- (BOOL)hasIsExtension;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBUninterpretedOption_NamePart_Builder *)builder;
+ (PBUninterpretedOption_NamePart_Builder *)builder;
+ (PBUninterpretedOption_NamePart_Builder *)builderWithPrototype:(PBUninterpretedOption_NamePart *)prototype;
- (PBUninterpretedOption_NamePart_Builder *)toBuilder;

+ (PBUninterpretedOption_NamePart *)parseFromData:(NSData *)data;
+ (PBUninterpretedOption_NamePart *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBUninterpretedOption_NamePart *)parseFromInputStream:(NSInputStream *)input;
+ (PBUninterpretedOption_NamePart *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBUninterpretedOption_NamePart *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBUninterpretedOption_NamePart *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBUninterpretedOption_NamePart_Builder : PBGeneratedMessage_Builder

- (PBUninterpretedOption_NamePart_Builder *)clear;
- (PBUninterpretedOption_NamePart_Builder *)clone;

- (PBUninterpretedOption_NamePart *)build;
- (PBUninterpretedOption_NamePart *)buildPartial;

- (PBUninterpretedOption_NamePart_Builder *)mergeFrom:(PBUninterpretedOption_NamePart *)other;
- (PBUninterpretedOption_NamePart_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBUninterpretedOption_NamePart_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasNamePart;
- (NSString *)namePart;
- (PBUninterpretedOption_NamePart_Builder *)setNamePart:(NSString *)value;
- (PBUninterpretedOption_NamePart_Builder *)clearNamePart;

- (BOOL)hasIsExtension;
- (BOOL)isExtension;
- (PBUninterpretedOption_NamePart_Builder *)setIsExtension:(BOOL)value;
- (PBUninterpretedOption_NamePart_Builder *)clearIsExtension;

@end


@interface PBUninterpretedOption_Builder : PBGeneratedMessage_Builder

- (PBUninterpretedOption_Builder *)clear;
- (PBUninterpretedOption_Builder *)clone;

- (PBUninterpretedOption *)build;
- (PBUninterpretedOption *)buildPartial;

- (PBUninterpretedOption_Builder *)mergeFrom:(PBUninterpretedOption *)other;
- (PBUninterpretedOption_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBUninterpretedOption_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)name;
- (PBUninterpretedOption_NamePart *)nameAtIndex:(NSUInteger)index;
- (PBUninterpretedOption_Builder *)addName:(PBUninterpretedOption_NamePart *)value;
- (PBUninterpretedOption_Builder *)setNameArray:(NSArray *)array;
- (PBUninterpretedOption_Builder *)clearName;

- (BOOL)hasIdentifierValue;
- (NSString *)identifierValue;
- (PBUninterpretedOption_Builder *)setIdentifierValue:(NSString *)value;
- (PBUninterpretedOption_Builder *)clearIdentifierValue;

- (BOOL)hasPositiveIntValue;
- (uint64_t)positiveIntValue;
- (PBUninterpretedOption_Builder *)setPositiveIntValue:(uint64_t)value;
- (PBUninterpretedOption_Builder *)clearPositiveIntValue;

- (BOOL)hasNegativeIntValue;
- (int64_t)negativeIntValue;
- (PBUninterpretedOption_Builder *)setNegativeIntValue:(int64_t)value;
- (PBUninterpretedOption_Builder *)clearNegativeIntValue;

- (BOOL)hasDoubleValue;
- (Float64)doubleValue;
- (PBUninterpretedOption_Builder *)setDoubleValue:(Float64)value;
- (PBUninterpretedOption_Builder *)clearDoubleValue;

- (BOOL)hasStringValue;
- (NSData *)stringValue;
- (PBUninterpretedOption_Builder *)setStringValue:(NSData *)value;
- (PBUninterpretedOption_Builder *)clearStringValue;

- (BOOL)hasAggregateValue;
- (NSString *)aggregateValue;
- (PBUninterpretedOption_Builder *)setAggregateValue:(NSString *)value;
- (PBUninterpretedOption_Builder *)clearAggregateValue;

@end


@interface PBSourceCodeInfo : PBGeneratedMessage {
@private
}

@property (nonatomic, strong) NSMutableArray *location;
- (PBSourceCodeInfo_Location *)locationAtIndex:(NSUInteger)index;
- (void)addLocation:(PBSourceCodeInfo_Location *)value;
- (void)addLocationArray:(NSArray *)array;
- (void)setLocationArray:(NSArray *)array;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBSourceCodeInfo_Builder *)builder;
+ (PBSourceCodeInfo_Builder *)builder;
+ (PBSourceCodeInfo_Builder *)builderWithPrototype:(PBSourceCodeInfo *)prototype;
- (PBSourceCodeInfo_Builder *)toBuilder;

+ (PBSourceCodeInfo *)parseFromData:(NSData *)data;
+ (PBSourceCodeInfo *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBSourceCodeInfo *)parseFromInputStream:(NSInputStream *)input;
+ (PBSourceCodeInfo *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBSourceCodeInfo *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBSourceCodeInfo *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBSourceCodeInfo_Location : PBGeneratedMessage {
@private
  int32_t _pathMemoizedSerializedSize;
  int32_t _spanMemoizedSerializedSize;
}

@property (nonatomic, strong) PBAppendableArray *path;

@property (nonatomic, strong) PBAppendableArray *span;

- (int32_t)pathAtIndex:(NSUInteger)index;
- (void)addPath:(int32_t)value;
- (void)addPathArray:(NSArray *)array;
- (void)setPathArray:(NSArray *)array;
- (void)setPathValues:(const int32_t *)values count:(NSUInteger)count;
- (void)clearPath;
- (int32_t)spanAtIndex:(NSUInteger)index;
- (void)addSpan:(int32_t)value;
- (void)addSpanArray:(NSArray *)array;
- (void)setSpanArray:(NSArray *)array;
- (void)setSpanValues:(const int32_t *)values count:(NSUInteger)count;
- (void)clearSpan;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (PBSourceCodeInfo_Location_Builder *)builder;
+ (PBSourceCodeInfo_Location_Builder *)builder;
+ (PBSourceCodeInfo_Location_Builder *)builderWithPrototype:(PBSourceCodeInfo_Location *)prototype;
- (PBSourceCodeInfo_Location_Builder *)toBuilder;

+ (PBSourceCodeInfo_Location *)parseFromData:(NSData *)data;
+ (PBSourceCodeInfo_Location *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBSourceCodeInfo_Location *)parseFromInputStream:(NSInputStream *)input;
+ (PBSourceCodeInfo_Location *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (PBSourceCodeInfo_Location *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (PBSourceCodeInfo_Location *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface PBSourceCodeInfo_Location_Builder : PBGeneratedMessage_Builder

- (PBSourceCodeInfo_Location_Builder *)clear;
- (PBSourceCodeInfo_Location_Builder *)clone;

- (PBSourceCodeInfo_Location *)build;
- (PBSourceCodeInfo_Location *)buildPartial;

- (PBSourceCodeInfo_Location_Builder *)mergeFrom:(PBSourceCodeInfo_Location *)other;
- (PBSourceCodeInfo_Location_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBSourceCodeInfo_Location_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)path;
- (int32_t)pathAtIndex:(NSUInteger)index;
- (PBSourceCodeInfo_Location_Builder *)addPath:(int32_t)value;
- (PBSourceCodeInfo_Location_Builder *)setPathArray:(NSArray *)array;
- (PBSourceCodeInfo_Location_Builder *)setPathValues:(const int32_t *)values count:(NSUInteger)count;
- (PBSourceCodeInfo_Location_Builder *)clearPath;

- (NSMutableArray *)span;
- (int32_t)spanAtIndex:(NSUInteger)index;
- (PBSourceCodeInfo_Location_Builder *)addSpan:(int32_t)value;
- (PBSourceCodeInfo_Location_Builder *)setSpanArray:(NSArray *)array;
- (PBSourceCodeInfo_Location_Builder *)setSpanValues:(const int32_t *)values count:(NSUInteger)count;
- (PBSourceCodeInfo_Location_Builder *)clearSpan;

@end


@interface PBSourceCodeInfo_Builder : PBGeneratedMessage_Builder

- (PBSourceCodeInfo_Builder *)clear;
- (PBSourceCodeInfo_Builder *)clone;

- (PBSourceCodeInfo *)build;
- (PBSourceCodeInfo *)buildPartial;

- (PBSourceCodeInfo_Builder *)mergeFrom:(PBSourceCodeInfo *)other;
- (PBSourceCodeInfo_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (PBSourceCodeInfo_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)location;
- (PBSourceCodeInfo_Location *)locationAtIndex:(NSUInteger)index;
- (PBSourceCodeInfo_Builder *)addLocation:(PBSourceCodeInfo_Location *)value;
- (PBSourceCodeInfo_Builder *)setLocationArray:(NSArray *)array;
- (PBSourceCodeInfo_Builder *)clearLocation;

@end


