// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Unittest_no_generic_services.pb.h"


@implementation UnittestNoGenericServicesRoot

static id<PBExtensionField> UnittestNoGenericServicesRoot_testExtension = nil;
static PBExtensionRegistry *extensionRegistry = nil;

+ (PBExtensionRegistry *)extensionRegistry
{
  return extensionRegistry;
}

+ (void)initialize {
  if (self == [UnittestNoGenericServicesRoot class]) {
    UnittestNoGenericServicesRoot_testExtension = [PBConcreteExtensionField
      extensionWithType:PBExtensionTypeInt32
      extendedClass:[TestMessage class]
      fieldNumber:1000
      defaultValue:@(0)
      messageOrGroupClass:[NSNumber class]
      isRepeated:NO
      isPacked:NO
      isMessageSetWireFormat:NO];
    PBMutableExtensionRegistry *registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}

+ (void)registerAllExtensions:(PBMutableExtensionRegistry *)registry
{
  [registry addExtension:UnittestNoGenericServicesRoot_testExtension];
}

+ (id<PBExtensionField>)testExtension
{
  return UnittestNoGenericServicesRoot_testExtension;
}
@end


BOOL TestEnumIsValidValue(TestEnum value)
{
  return YES;
}

NSString *TestEnumToString(TestEnum value)
{
  switch (value) {
    case TestEnumFoo:
      return @"FOO";
    default:
      return [NSString stringWithFormat:@"%d", (int)value];
  }
}


@interface TestMessage ()


@end


@implementation TestMessage

- (BOOL)hasA
{
  return _hasA;
}

- (void)setA:(int32_t)value
{
  _hasA = YES;
  _a = value;
}

- (void)clearA
{
  _hasA = NO;
  _a = 0;
}

- (instancetype)init
{
  if ((self = [super init])) {
    _a = 0;
  }
  return self;
}

- (BOOL)isInitialized
{
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}

- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output
{
  if (self.hasA) {
    [output writeInt32:1 value:self.a];
  }
  [self writeExtensionsToCodedOutputStream:output from:1000 to:536870912];
  [self.unknownFields writeToCodedOutputStream:output];
}

- (int32_t)serializedSize
{
  int32_t size_ = 0;
  if (self.hasA) {
    size_ += computeInt32Size(1, self.a);
  }
  size_ += [self extensionsSerializedSize];
  size_ += self.unknownFields.serializedSize;
  return size_;
}

+ (TestMessage *)parseFromData:(NSData *)data
{
  return (TestMessage *)[[[TestMessage builder] mergeFromData:data] build];
}

+ (TestMessage *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestMessage*)[[[TestMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}

+ (TestMessage *)parseFromInputStream:(NSInputStream *)input
{
  return (TestMessage*)[[[TestMessage builder] mergeFromInputStream:input] build];
}

+ (TestMessage *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestMessage*)[[[TestMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestMessage *)parseFromCodedInputStream:(PBCodedInputStream *)input
{
  return [[[TestMessage builder] mergeFromCodedInputStream:input] build];
}

+ (TestMessage *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return [[[TestMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestMessage_Builder *)builder
{
  return [[TestMessage_Builder alloc] init];
}

+ (TestMessage_Builder *)builderWithPrototype:(TestMessage *)prototype
{
  return [[TestMessage builder] mergeFrom:prototype];
}

- (TestMessage_Builder *)builder
{
  return [TestMessage builder];
}

- (TestMessage_Builder *)toBuilder
{
  return [TestMessage builderWithPrototype:self];
}

- (void)writeDescriptionTo:(NSMutableString *)output withIndent:(NSString *)indent
{
  if (self.hasA) {
    [output appendFormat:@"%@%@: %@\n", indent, @"a", @(self.a)];
  }
  [self writeExtensionDescriptionToMutableString:(NSMutableString*)output from:1000 to:536870912 withIndent:indent];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}

- (BOOL)isEqual:(id)other
{
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessage class]]) {
    return NO;
  }
  TestMessage *otherMessage = other;
  return
    (self.hasA == otherMessage.hasA && (!self.hasA || self.a == otherMessage.a)) &&
    [self isEqualExtensionsInOther:otherMessage from:1000 to:536870912] &&

    (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}

- (NSUInteger)hash
{
  NSUInteger hashCode = 7;
  if (self.hasA) {
    hashCode = hashCode * 31 + [@(self.a) hash];
  }
  hashCode = hashCode * 31 + [self hashExtensionsFrom:1000 to:536870912];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}

@end


@interface TestMessage_Builder()

@property (strong) TestMessage *result;

@end


@implementation TestMessage_Builder

- (instancetype)init
{
  if ((self = [super init])) {
    self.result = [[TestMessage alloc] init];
  }
  return self;
}

- (PBExtendableMessage *)internalGetResult
{
  return _result;
}

- (TestMessage_Builder *)clear
{
  self.result = [[TestMessage alloc] init];
  return self;
}

- (TestMessage_Builder *)clone
{
  return [TestMessage builderWithPrototype:_result];
}

- (TestMessage *)build
{
  [self checkInitialized];
  return [self buildPartial];
}

- (TestMessage *)buildPartial
{
  TestMessage *returnMe = _result;
  self.result = nil;
  return returnMe;
}

- (TestMessage_Builder *)mergeFrom:(TestMessage *)other
{
  if (other == nil) {
    return self;
  }
  if (other.hasA) {
    [self setA:other.a];
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}

- (TestMessage_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input
{
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}

- (TestMessage_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry*)extensionRegistry
{
  PBUnknownFieldSet_Builder *unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setA:[input readInt32]];
        break;
      }
    }
  }
}

- (BOOL)hasA
{
  return _result.hasA;
}

- (int32_t)a
{
  return _result.a;
}

- (TestMessage_Builder*)setA:(int32_t)value
{
  _result.a = value;
  return self;
}

- (TestMessage_Builder*)clearA
{
  [_result clearA];
  return self;
}

@end


