// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Unittest_optimize_for.pb.h"


@implementation UnittestOptimizeForRoot

static id<PBExtensionField> TestOptimizedForSize_testExtension = nil;
static id<PBExtensionField> TestOptimizedForSize_testExtension2 = nil;
static PBExtensionRegistry *extensionRegistry = nil;

+ (PBExtensionRegistry *)extensionRegistry
{
  return extensionRegistry;
}

+ (void)initialize {
  if (self == [UnittestOptimizeForRoot class]) {
    TestOptimizedForSize_testExtension = [PBConcreteExtensionField
      extensionWithType:PBExtensionTypeInt32
      extendedClass:[TestOptimizedForSize class]
      fieldNumber:1234
      defaultValue:@(0)
      messageOrGroupClass:[NSNumber class]
      isRepeated:NO
      isPacked:NO
      isMessageSetWireFormat:NO];
    TestOptimizedForSize_testExtension2 = [PBConcreteExtensionField
      extensionWithType:PBExtensionTypeMessage
      extendedClass:[TestOptimizedForSize class]
      fieldNumber:1235
      defaultValue:nil
      messageOrGroupClass:[TestRequiredOptimizedForSize class]
      isRepeated:NO
      isPacked:NO
      isMessageSetWireFormat:NO];
    PBMutableExtensionRegistry *registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [UnittestRoot registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}

+ (void)registerAllExtensions:(PBMutableExtensionRegistry *)registry
{
  [registry addExtension:TestOptimizedForSize_testExtension];
  [registry addExtension:TestOptimizedForSize_testExtension2];
}

@end


@interface TestOptimizedForSize ()


@end


@implementation TestOptimizedForSize

- (BOOL)hasI
{
  return _hasI;
}

- (void)setI:(int32_t)value
{
  _hasI = YES;
  _i = value;
}

- (void)clearI
{
  _hasI = NO;
  _i = 0;
}

- (BOOL)hasMsg
{
  return _hasMsg;
}

- (void)setMsg:(ForeignMessage *)value
{
  _hasMsg = value != nil;
  _msg = value;
}

- (void)clearMsg
{
  _hasMsg = NO;
  _msg = nil;
}

- (instancetype)init
{
  if ((self = [super init])) {
    _i = 0;
    _msg = nil;
  }
  return self;
}

+ (id<PBExtensionField>)testExtension
{
  return TestOptimizedForSize_testExtension;
}
+ (id<PBExtensionField>)testExtension2
{
  return TestOptimizedForSize_testExtension2;
}
- (BOOL)isInitialized
{
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}

- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output
{
  if (self.hasI) {
    [output writeInt32:1 value:self.i];
  }
  if (self.hasMsg) {
    [output writeMessage:19 value:self.msg];
  }
  [self writeExtensionsToCodedOutputStream:output from:1000 to:536870912];
  [self.unknownFields writeToCodedOutputStream:output];
}

- (int32_t)serializedSize
{
  int32_t size_ = 0;
  if (self.hasI) {
    size_ += computeInt32Size(1, self.i);
  }
  if (self.hasMsg) {
    size_ += computeMessageSize(19, self.msg);
  }
  size_ += [self extensionsSerializedSize];
  size_ += self.unknownFields.serializedSize;
  return size_;
}

+ (TestOptimizedForSize *)parseFromData:(NSData *)data
{
  return (TestOptimizedForSize *)[[[TestOptimizedForSize builder] mergeFromData:data] build];
}

+ (TestOptimizedForSize *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestOptimizedForSize*)[[[TestOptimizedForSize builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}

+ (TestOptimizedForSize *)parseFromInputStream:(NSInputStream *)input
{
  return (TestOptimizedForSize*)[[[TestOptimizedForSize builder] mergeFromInputStream:input] build];
}

+ (TestOptimizedForSize *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestOptimizedForSize*)[[[TestOptimizedForSize builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input
{
  return [[[TestOptimizedForSize builder] mergeFromCodedInputStream:input] build];
}

+ (TestOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return [[[TestOptimizedForSize builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestOptimizedForSize_Builder *)builder
{
  return [[TestOptimizedForSize_Builder alloc] init];
}

+ (TestOptimizedForSize_Builder *)builderWithPrototype:(TestOptimizedForSize *)prototype
{
  return [[TestOptimizedForSize builder] mergeFrom:prototype];
}

- (TestOptimizedForSize_Builder *)builder
{
  return [TestOptimizedForSize builder];
}

- (TestOptimizedForSize_Builder *)toBuilder
{
  return [TestOptimizedForSize builderWithPrototype:self];
}

- (void)writeDescriptionTo:(NSMutableString *)output withIndent:(NSString *)indent
{
  if (self.hasI) {
    [output appendFormat:@"%@%@: %@\n", indent, @"i", @(self.i)];
  }
  if (self.hasMsg) {
    [output appendFormat:@"%@%@ {\n", indent, @"msg"];
    [self.msg writeDescriptionTo:output withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self writeExtensionDescriptionToMutableString:(NSMutableString*)output from:1000 to:536870912 withIndent:indent];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}

- (BOOL)isEqual:(id)other
{
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestOptimizedForSize class]]) {
    return NO;
  }
  TestOptimizedForSize *otherMessage = other;
  return
    (self.hasI == otherMessage.hasI && (!self.hasI || self.i == otherMessage.i)) &&
    (self.hasMsg == otherMessage.hasMsg && (!self.hasMsg || [self.msg isEqual:otherMessage.msg])) &&
    [self isEqualExtensionsInOther:otherMessage from:1000 to:536870912] &&

    (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}

- (NSUInteger)hash
{
  NSUInteger hashCode = 7;
  if (self.hasI) {
    hashCode = hashCode * 31 + [@(self.i) hash];
  }
  if (self.hasMsg) {
    hashCode = hashCode * 31 + [self.msg hash];
  }
  hashCode = hashCode * 31 + [self hashExtensionsFrom:1000 to:536870912];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}

@end


@interface TestOptimizedForSize_Builder()

@property (strong) TestOptimizedForSize *result;

@end


@implementation TestOptimizedForSize_Builder

- (instancetype)init
{
  if ((self = [super init])) {
    self.result = [[TestOptimizedForSize alloc] init];
  }
  return self;
}

- (PBExtendableMessage *)internalGetResult
{
  return _result;
}

- (TestOptimizedForSize_Builder *)clear
{
  self.result = [[TestOptimizedForSize alloc] init];
  return self;
}

- (TestOptimizedForSize_Builder *)clone
{
  return [TestOptimizedForSize builderWithPrototype:_result];
}

- (TestOptimizedForSize *)build
{
  [self checkInitialized];
  return [self buildPartial];
}

- (TestOptimizedForSize *)buildPartial
{
  TestOptimizedForSize *returnMe = _result;
  self.result = nil;
  return returnMe;
}

- (TestOptimizedForSize_Builder *)mergeFrom:(TestOptimizedForSize *)other
{
  if (other == nil) {
    return self;
  }
  if (other.hasI) {
    [self setI:other.i];
  }
  if (other.hasMsg) {
    [self mergeMsg:other.msg];
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}

- (TestOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input
{
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}

- (TestOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry*)extensionRegistry
{
  PBUnknownFieldSet_Builder *unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setI:[input readInt32]];
        break;
      }
      case 154: {
        ForeignMessage_Builder *subBuilder = [ForeignMessage builder];
        if (self.hasMsg) {
          [subBuilder mergeFrom:self.msg];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setMsg:[subBuilder buildPartial]];
        break;
      }
    }
  }
}

- (BOOL)hasI
{
  return _result.hasI;
}

- (int32_t)i
{
  return _result.i;
}

- (TestOptimizedForSize_Builder*)setI:(int32_t)value
{
  _result.i = value;
  return self;
}

- (TestOptimizedForSize_Builder*)clearI
{
  [_result clearI];
  return self;
}

- (BOOL)hasMsg
{
  return _result.hasMsg;
}

- (ForeignMessage *)msg
{
  return _result.msg;
}

- (TestOptimizedForSize_Builder *)setMsg:(ForeignMessage *)value
{
  _result.msg = value;
  return self;
}

- (TestOptimizedForSize_Builder *)setMsgBuilder:(ForeignMessage_Builder *)builderForValue
{
  return [self setMsg:[builderForValue build]];
}

- (TestOptimizedForSize_Builder *)mergeMsg:(ForeignMessage *)value
{
  if (_result.hasMsg && _result.msg != nil) {
    _result.msg = [[[ForeignMessage builderWithPrototype:_result.msg] mergeFrom:value] buildPartial];
  } else {
    _result.msg = value;
  }
  return self;
}

- (TestOptimizedForSize_Builder *)clearMsg
{
  [_result clearMsg];
  return self;
}

@end


@interface TestRequiredOptimizedForSize ()


@end


@implementation TestRequiredOptimizedForSize

- (BOOL)hasX
{
  return _hasX;
}

- (void)setX:(int32_t)value
{
  _hasX = YES;
  _x = value;
}

- (void)clearX
{
  _hasX = NO;
  _x = 0;
}

- (instancetype)init
{
  if ((self = [super init])) {
    _x = 0;
  }
  return self;
}

- (BOOL)isInitialized
{
  if (!self.hasX) {
    return NO;
  }
  return YES;
}

- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output
{
  if (self.hasX) {
    [output writeInt32:1 value:self.x];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}

- (int32_t)serializedSize
{
  int32_t size_ = 0;
  if (self.hasX) {
    size_ += computeInt32Size(1, self.x);
  }
  size_ += self.unknownFields.serializedSize;
  return size_;
}

+ (TestRequiredOptimizedForSize *)parseFromData:(NSData *)data
{
  return (TestRequiredOptimizedForSize *)[[[TestRequiredOptimizedForSize builder] mergeFromData:data] build];
}

+ (TestRequiredOptimizedForSize *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestRequiredOptimizedForSize*)[[[TestRequiredOptimizedForSize builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}

+ (TestRequiredOptimizedForSize *)parseFromInputStream:(NSInputStream *)input
{
  return (TestRequiredOptimizedForSize*)[[[TestRequiredOptimizedForSize builder] mergeFromInputStream:input] build];
}

+ (TestRequiredOptimizedForSize *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestRequiredOptimizedForSize*)[[[TestRequiredOptimizedForSize builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestRequiredOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input
{
  return [[[TestRequiredOptimizedForSize builder] mergeFromCodedInputStream:input] build];
}

+ (TestRequiredOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return [[[TestRequiredOptimizedForSize builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestRequiredOptimizedForSize_Builder *)builder
{
  return [[TestRequiredOptimizedForSize_Builder alloc] init];
}

+ (TestRequiredOptimizedForSize_Builder *)builderWithPrototype:(TestRequiredOptimizedForSize *)prototype
{
  return [[TestRequiredOptimizedForSize builder] mergeFrom:prototype];
}

- (TestRequiredOptimizedForSize_Builder *)builder
{
  return [TestRequiredOptimizedForSize builder];
}

- (TestRequiredOptimizedForSize_Builder *)toBuilder
{
  return [TestRequiredOptimizedForSize builderWithPrototype:self];
}

- (void)writeDescriptionTo:(NSMutableString *)output withIndent:(NSString *)indent
{
  if (self.hasX) {
    [output appendFormat:@"%@%@: %@\n", indent, @"x", @(self.x)];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}

- (BOOL)isEqual:(id)other
{
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestRequiredOptimizedForSize class]]) {
    return NO;
  }
  TestRequiredOptimizedForSize *otherMessage = other;
  return
    (self.hasX == otherMessage.hasX && (!self.hasX || self.x == otherMessage.x)) &&
    (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}

- (NSUInteger)hash
{
  NSUInteger hashCode = 7;
  if (self.hasX) {
    hashCode = hashCode * 31 + [@(self.x) hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}

@end


@interface TestRequiredOptimizedForSize_Builder()

@property (strong) TestRequiredOptimizedForSize *result;

@end


@implementation TestRequiredOptimizedForSize_Builder

- (instancetype)init
{
  if ((self = [super init])) {
    self.result = [[TestRequiredOptimizedForSize alloc] init];
  }
  return self;
}

- (PBGeneratedMessage *)internalGetResult
{
  return _result;
}

- (TestRequiredOptimizedForSize_Builder *)clear
{
  self.result = [[TestRequiredOptimizedForSize alloc] init];
  return self;
}

- (TestRequiredOptimizedForSize_Builder *)clone
{
  return [TestRequiredOptimizedForSize builderWithPrototype:_result];
}

- (TestRequiredOptimizedForSize *)build
{
  [self checkInitialized];
  return [self buildPartial];
}

- (TestRequiredOptimizedForSize *)buildPartial
{
  TestRequiredOptimizedForSize *returnMe = _result;
  self.result = nil;
  return returnMe;
}

- (TestRequiredOptimizedForSize_Builder *)mergeFrom:(TestRequiredOptimizedForSize *)other
{
  if (other == nil) {
    return self;
  }
  if (other.hasX) {
    [self setX:other.x];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}

- (TestRequiredOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input
{
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}

- (TestRequiredOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry*)extensionRegistry
{
  PBUnknownFieldSet_Builder *unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setX:[input readInt32]];
        break;
      }
    }
  }
}

- (BOOL)hasX
{
  return _result.hasX;
}

- (int32_t)x
{
  return _result.x;
}

- (TestRequiredOptimizedForSize_Builder*)setX:(int32_t)value
{
  _result.x = value;
  return self;
}

- (TestRequiredOptimizedForSize_Builder*)clearX
{
  [_result clearX];
  return self;
}

@end


@interface TestOptionalOptimizedForSize ()


@end


@implementation TestOptionalOptimizedForSize

- (BOOL)hasO
{
  return _hasO;
}

- (void)setO:(TestRequiredOptimizedForSize *)value
{
  _hasO = value != nil;
  _o = value;
}

- (void)clearO
{
  _hasO = NO;
  _o = nil;
}

- (instancetype)init
{
  if ((self = [super init])) {
    _o = nil;
  }
  return self;
}

- (BOOL)isInitialized
{
  if (self.hasO && !self.o.isInitialized) {
    return NO;
  }
  return YES;
}

- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output
{
  if (self.hasO) {
    [output writeMessage:1 value:self.o];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}

- (int32_t)serializedSize
{
  int32_t size_ = 0;
  if (self.hasO) {
    size_ += computeMessageSize(1, self.o);
  }
  size_ += self.unknownFields.serializedSize;
  return size_;
}

+ (TestOptionalOptimizedForSize *)parseFromData:(NSData *)data
{
  return (TestOptionalOptimizedForSize *)[[[TestOptionalOptimizedForSize builder] mergeFromData:data] build];
}

+ (TestOptionalOptimizedForSize *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestOptionalOptimizedForSize*)[[[TestOptionalOptimizedForSize builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}

+ (TestOptionalOptimizedForSize *)parseFromInputStream:(NSInputStream *)input
{
  return (TestOptionalOptimizedForSize*)[[[TestOptionalOptimizedForSize builder] mergeFromInputStream:input] build];
}

+ (TestOptionalOptimizedForSize *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return (TestOptionalOptimizedForSize*)[[[TestOptionalOptimizedForSize builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestOptionalOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input
{
  return [[[TestOptionalOptimizedForSize builder] mergeFromCodedInputStream:input] build];
}

+ (TestOptionalOptimizedForSize *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry
{
  return [[[TestOptionalOptimizedForSize builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}

+ (TestOptionalOptimizedForSize_Builder *)builder
{
  return [[TestOptionalOptimizedForSize_Builder alloc] init];
}

+ (TestOptionalOptimizedForSize_Builder *)builderWithPrototype:(TestOptionalOptimizedForSize *)prototype
{
  return [[TestOptionalOptimizedForSize builder] mergeFrom:prototype];
}

- (TestOptionalOptimizedForSize_Builder *)builder
{
  return [TestOptionalOptimizedForSize builder];
}

- (TestOptionalOptimizedForSize_Builder *)toBuilder
{
  return [TestOptionalOptimizedForSize builderWithPrototype:self];
}

- (void)writeDescriptionTo:(NSMutableString *)output withIndent:(NSString *)indent
{
  if (self.hasO) {
    [output appendFormat:@"%@%@ {\n", indent, @"o"];
    [self.o writeDescriptionTo:output withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}

- (BOOL)isEqual:(id)other
{
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestOptionalOptimizedForSize class]]) {
    return NO;
  }
  TestOptionalOptimizedForSize *otherMessage = other;
  return
    (self.hasO == otherMessage.hasO && (!self.hasO || [self.o isEqual:otherMessage.o])) &&
    (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}

- (NSUInteger)hash
{
  NSUInteger hashCode = 7;
  if (self.hasO) {
    hashCode = hashCode * 31 + [self.o hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}

@end


@interface TestOptionalOptimizedForSize_Builder()

@property (strong) TestOptionalOptimizedForSize *result;

@end


@implementation TestOptionalOptimizedForSize_Builder

- (instancetype)init
{
  if ((self = [super init])) {
    self.result = [[TestOptionalOptimizedForSize alloc] init];
  }
  return self;
}

- (PBGeneratedMessage *)internalGetResult
{
  return _result;
}

- (TestOptionalOptimizedForSize_Builder *)clear
{
  self.result = [[TestOptionalOptimizedForSize alloc] init];
  return self;
}

- (TestOptionalOptimizedForSize_Builder *)clone
{
  return [TestOptionalOptimizedForSize builderWithPrototype:_result];
}

- (TestOptionalOptimizedForSize *)build
{
  [self checkInitialized];
  return [self buildPartial];
}

- (TestOptionalOptimizedForSize *)buildPartial
{
  TestOptionalOptimizedForSize *returnMe = _result;
  self.result = nil;
  return returnMe;
}

- (TestOptionalOptimizedForSize_Builder *)mergeFrom:(TestOptionalOptimizedForSize *)other
{
  if (other == nil) {
    return self;
  }
  if (other.hasO) {
    [self mergeO:other.o];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}

- (TestOptionalOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input
{
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}

- (TestOptionalOptimizedForSize_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry*)extensionRegistry
{
  PBUnknownFieldSet_Builder *unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        TestRequiredOptimizedForSize_Builder *subBuilder = [TestRequiredOptimizedForSize builder];
        if (self.hasO) {
          [subBuilder mergeFrom:self.o];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setO:[subBuilder buildPartial]];
        break;
      }
    }
  }
}

- (BOOL)hasO
{
  return _result.hasO;
}

- (TestRequiredOptimizedForSize *)o
{
  return _result.o;
}

- (TestOptionalOptimizedForSize_Builder *)setO:(TestRequiredOptimizedForSize *)value
{
  _result.o = value;
  return self;
}

- (TestOptionalOptimizedForSize_Builder *)setOBuilder:(TestRequiredOptimizedForSize_Builder *)builderForValue
{
  return [self setO:[builderForValue build]];
}

- (TestOptionalOptimizedForSize_Builder *)mergeO:(TestRequiredOptimizedForSize *)value
{
  if (_result.hasO && _result.o != nil) {
    _result.o = [[[TestRequiredOptimizedForSize builderWithPrototype:_result.o] mergeFrom:value] buildPartial];
  } else {
    _result.o = value;
  }
  return self;
}

- (TestOptionalOptimizedForSize_Builder *)clearO
{
  [_result clearO];
  return self;
}

@end


