// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Unittest_import_lite.pb.h"

@class ForeignMessageLite;
@class ForeignMessageLite_Builder;
@class ImportMessageLite;
@class ImportMessageLite_Builder;
@class OptionalGroup_extension_lite;
@class OptionalGroup_extension_lite_Builder;
@class RepeatedGroup_extension_lite;
@class RepeatedGroup_extension_lite_Builder;
@class TestAllExtensionsLite;
@class TestAllExtensionsLite_Builder;
@class TestAllTypesLite;
@class TestAllTypesLite_Builder;
@class TestAllTypesLite_NestedMessage;
@class TestAllTypesLite_NestedMessage_Builder;
@class TestAllTypesLite_OptionalGroup;
@class TestAllTypesLite_OptionalGroup_Builder;
@class TestAllTypesLite_RepeatedGroup;
@class TestAllTypesLite_RepeatedGroup_Builder;
@class TestDeprecatedLite;
@class TestDeprecatedLite_Builder;
@class TestNestedExtensionLite;
@class TestNestedExtensionLite_Builder;
@class TestPackedExtensionsLite;
@class TestPackedExtensionsLite_Builder;
@class TestPackedTypesLite;
@class TestPackedTypesLite_Builder;


#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


typedef enum {
  ForeignEnumLiteForeignLiteFoo = 4,
  ForeignEnumLiteForeignLiteBar = 5,
  ForeignEnumLiteForeignLiteBaz = 6,
} ForeignEnumLite;

BOOL ForeignEnumLiteIsValidValue(ForeignEnumLite value);
NSString *ForeignEnumLiteToString(ForeignEnumLite value);


typedef enum {
  TestAllTypesLite_NestedEnumFoo = 1,
  TestAllTypesLite_NestedEnumBar = 2,
  TestAllTypesLite_NestedEnumBaz = 3,
} TestAllTypesLite_NestedEnum;

BOOL TestAllTypesLite_NestedEnumIsValidValue(TestAllTypesLite_NestedEnum value);
NSString *TestAllTypesLite_NestedEnumToString(TestAllTypesLite_NestedEnum value);


@interface UnittestLiteRoot : NSObject

+ (PBExtensionRegistry *)extensionRegistry;
+ (void)registerAllExtensions:(PBMutableExtensionRegistry *)registry;
+ (id<PBExtensionField>)optionalInt32ExtensionLite;
+ (id<PBExtensionField>)optionalInt64ExtensionLite;
+ (id<PBExtensionField>)optionalUint32ExtensionLite;
+ (id<PBExtensionField>)optionalUint64ExtensionLite;
+ (id<PBExtensionField>)optionalSint32ExtensionLite;
+ (id<PBExtensionField>)optionalSint64ExtensionLite;
+ (id<PBExtensionField>)optionalFixed32ExtensionLite;
+ (id<PBExtensionField>)optionalFixed64ExtensionLite;
+ (id<PBExtensionField>)optionalSfixed32ExtensionLite;
+ (id<PBExtensionField>)optionalSfixed64ExtensionLite;
+ (id<PBExtensionField>)optionalFloatExtensionLite;
+ (id<PBExtensionField>)optionalDoubleExtensionLite;
+ (id<PBExtensionField>)optionalBoolExtensionLite;
+ (id<PBExtensionField>)optionalStringExtensionLite;
+ (id<PBExtensionField>)optionalBytesExtensionLite;
+ (id<PBExtensionField>)optionalGroupExtensionLite;
+ (id<PBExtensionField>)optionalNestedMessageExtensionLite;
+ (id<PBExtensionField>)optionalForeignMessageExtensionLite;
+ (id<PBExtensionField>)optionalImportMessageExtensionLite;
+ (id<PBExtensionField>)optionalNestedEnumExtensionLite;
+ (id<PBExtensionField>)optionalForeignEnumExtensionLite;
+ (id<PBExtensionField>)optionalImportEnumExtensionLite;
+ (id<PBExtensionField>)optionalStringPieceExtensionLite;
+ (id<PBExtensionField>)optionalCordExtensionLite;
+ (id<PBExtensionField>)repeatedInt32ExtensionLite;
+ (id<PBExtensionField>)repeatedInt64ExtensionLite;
+ (id<PBExtensionField>)repeatedUint32ExtensionLite;
+ (id<PBExtensionField>)repeatedUint64ExtensionLite;
+ (id<PBExtensionField>)repeatedSint32ExtensionLite;
+ (id<PBExtensionField>)repeatedSint64ExtensionLite;
+ (id<PBExtensionField>)repeatedFixed32ExtensionLite;
+ (id<PBExtensionField>)repeatedFixed64ExtensionLite;
+ (id<PBExtensionField>)repeatedSfixed32ExtensionLite;
+ (id<PBExtensionField>)repeatedSfixed64ExtensionLite;
+ (id<PBExtensionField>)repeatedFloatExtensionLite;
+ (id<PBExtensionField>)repeatedDoubleExtensionLite;
+ (id<PBExtensionField>)repeatedBoolExtensionLite;
+ (id<PBExtensionField>)repeatedStringExtensionLite;
+ (id<PBExtensionField>)repeatedBytesExtensionLite;
+ (id<PBExtensionField>)repeatedGroupExtensionLite;
+ (id<PBExtensionField>)repeatedNestedMessageExtensionLite;
+ (id<PBExtensionField>)repeatedForeignMessageExtensionLite;
+ (id<PBExtensionField>)repeatedImportMessageExtensionLite;
+ (id<PBExtensionField>)repeatedNestedEnumExtensionLite;
+ (id<PBExtensionField>)repeatedForeignEnumExtensionLite;
+ (id<PBExtensionField>)repeatedImportEnumExtensionLite;
+ (id<PBExtensionField>)repeatedStringPieceExtensionLite;
+ (id<PBExtensionField>)repeatedCordExtensionLite;
+ (id<PBExtensionField>)defaultInt32ExtensionLite;
+ (id<PBExtensionField>)defaultInt64ExtensionLite;
+ (id<PBExtensionField>)defaultUint32ExtensionLite;
+ (id<PBExtensionField>)defaultUint64ExtensionLite;
+ (id<PBExtensionField>)defaultSint32ExtensionLite;
+ (id<PBExtensionField>)defaultSint64ExtensionLite;
+ (id<PBExtensionField>)defaultFixed32ExtensionLite;
+ (id<PBExtensionField>)defaultFixed64ExtensionLite;
+ (id<PBExtensionField>)defaultSfixed32ExtensionLite;
+ (id<PBExtensionField>)defaultSfixed64ExtensionLite;
+ (id<PBExtensionField>)defaultFloatExtensionLite;
+ (id<PBExtensionField>)defaultDoubleExtensionLite;
+ (id<PBExtensionField>)defaultBoolExtensionLite;
+ (id<PBExtensionField>)defaultStringExtensionLite;
+ (id<PBExtensionField>)defaultBytesExtensionLite;
+ (id<PBExtensionField>)defaultNestedEnumExtensionLite;
+ (id<PBExtensionField>)defaultForeignEnumExtensionLite;
+ (id<PBExtensionField>)defaultImportEnumExtensionLite;
+ (id<PBExtensionField>)defaultStringPieceExtensionLite;
+ (id<PBExtensionField>)defaultCordExtensionLite;
+ (id<PBExtensionField>)packedInt32ExtensionLite;
+ (id<PBExtensionField>)packedInt64ExtensionLite;
+ (id<PBExtensionField>)packedUint32ExtensionLite;
+ (id<PBExtensionField>)packedUint64ExtensionLite;
+ (id<PBExtensionField>)packedSint32ExtensionLite;
+ (id<PBExtensionField>)packedSint64ExtensionLite;
+ (id<PBExtensionField>)packedFixed32ExtensionLite;
+ (id<PBExtensionField>)packedFixed64ExtensionLite;
+ (id<PBExtensionField>)packedSfixed32ExtensionLite;
+ (id<PBExtensionField>)packedSfixed64ExtensionLite;
+ (id<PBExtensionField>)packedFloatExtensionLite;
+ (id<PBExtensionField>)packedDoubleExtensionLite;
+ (id<PBExtensionField>)packedBoolExtensionLite;
+ (id<PBExtensionField>)packedEnumExtensionLite;

@end


@interface TestAllTypesLite : PBGeneratedMessage {
@private
  BOOL _hasDefaultBool:1;
  BOOL _hasOptionalBool:1;
  BOOL _hasDefaultDouble:1;
  BOOL _hasOptionalDouble:1;
  BOOL _hasDefaultFloat:1;
  BOOL _hasOptionalFloat:1;
  BOOL _hasOptionalInt64:1;
  BOOL _hasDefaultInt64:1;
  BOOL _hasOptionalUint64:1;
  BOOL _hasDefaultUint64:1;
  BOOL _hasOptionalInt32:1;
  BOOL _hasDefaultInt32:1;
  BOOL _hasOptionalFixed64:1;
  BOOL _hasDefaultFixed64:1;
  BOOL _hasOptionalFixed32:1;
  BOOL _hasDefaultFixed32:1;
  BOOL _hasDefaultCord:1;
  BOOL _hasOptionalStringPiece:1;
  BOOL _hasOptionalCord:1;
  BOOL _hasDefaultStringPiece:1;
  BOOL _hasDefaultString:1;
  BOOL _hasOptionalString:1;
  BOOL _hasOptionalGroup:1;
  BOOL _hasOptionalForeignMessage:1;
  BOOL _hasOptionalImportMessage:1;
  BOOL _hasOptionalNestedMessage:1;
  BOOL _hasDefaultBytes:1;
  BOOL _hasOptionalBytes:1;
  BOOL _hasOptionalUint32:1;
  BOOL _hasDefaultUint32:1;
  BOOL _hasOptionalNestedEnum:1;
  BOOL _hasOptionalForeignEnum:1;
  BOOL _hasOptionalImportEnum:1;
  BOOL _hasDefaultImportEnum:1;
  BOOL _hasDefaultForeignEnum:1;
  BOOL _hasDefaultNestedEnum:1;
  BOOL _hasDefaultSfixed32:1;
  BOOL _hasOptionalSfixed32:1;
  BOOL _hasDefaultSfixed64:1;
  BOOL _hasOptionalSfixed64:1;
  BOOL _hasOptionalSint32:1;
  BOOL _hasDefaultSint32:1;
  BOOL _hasOptionalSint64:1;
  BOOL _hasDefaultSint64:1;
}

@property (nonatomic) int32_t optionalInt32;
- (void)clearOptionalInt32;
- (BOOL)hasOptionalInt32;

@property (nonatomic) int64_t optionalInt64;
- (void)clearOptionalInt64;
- (BOOL)hasOptionalInt64;

@property (nonatomic) uint32_t optionalUint32;
- (void)clearOptionalUint32;
- (BOOL)hasOptionalUint32;

@property (nonatomic) uint64_t optionalUint64;
- (void)clearOptionalUint64;
- (BOOL)hasOptionalUint64;

@property (nonatomic) int32_t optionalSint32;
- (void)clearOptionalSint32;
- (BOOL)hasOptionalSint32;

@property (nonatomic) int64_t optionalSint64;
- (void)clearOptionalSint64;
- (BOOL)hasOptionalSint64;

@property (nonatomic) uint32_t optionalFixed32;
- (void)clearOptionalFixed32;
- (BOOL)hasOptionalFixed32;

@property (nonatomic) uint64_t optionalFixed64;
- (void)clearOptionalFixed64;
- (BOOL)hasOptionalFixed64;

@property (nonatomic) int32_t optionalSfixed32;
- (void)clearOptionalSfixed32;
- (BOOL)hasOptionalSfixed32;

@property (nonatomic) int64_t optionalSfixed64;
- (void)clearOptionalSfixed64;
- (BOOL)hasOptionalSfixed64;

@property (nonatomic) Float32 optionalFloat;
- (void)clearOptionalFloat;
- (BOOL)hasOptionalFloat;

@property (nonatomic) Float64 optionalDouble;
- (void)clearOptionalDouble;
- (BOOL)hasOptionalDouble;

@property (nonatomic) BOOL optionalBool;
- (void)clearOptionalBool;
- (BOOL)hasOptionalBool;

@property (nonatomic, strong) NSString *optionalString;
- (void)clearOptionalString;
- (BOOL)hasOptionalString;

@property (nonatomic, strong) NSData *optionalBytes;
- (void)clearOptionalBytes;
- (BOOL)hasOptionalBytes;

@property (nonatomic, strong) TestAllTypesLite_OptionalGroup *optionalGroup;
- (void)clearOptionalGroup;
- (BOOL)hasOptionalGroup;

@property (nonatomic, strong) TestAllTypesLite_NestedMessage *optionalNestedMessage;
- (void)clearOptionalNestedMessage;
- (BOOL)hasOptionalNestedMessage;

@property (nonatomic, strong) ForeignMessageLite *optionalForeignMessage;
- (void)clearOptionalForeignMessage;
- (BOOL)hasOptionalForeignMessage;

@property (nonatomic, strong) ImportMessageLite *optionalImportMessage;
- (void)clearOptionalImportMessage;
- (BOOL)hasOptionalImportMessage;

@property (nonatomic) TestAllTypesLite_NestedEnum optionalNestedEnum;
- (void)clearOptionalNestedEnum;
- (BOOL)hasOptionalNestedEnum;

@property (nonatomic) ForeignEnumLite optionalForeignEnum;
- (void)clearOptionalForeignEnum;
- (BOOL)hasOptionalForeignEnum;

@property (nonatomic) ImportEnumLite optionalImportEnum;
- (void)clearOptionalImportEnum;
- (BOOL)hasOptionalImportEnum;

@property (nonatomic, strong) NSString *optionalStringPiece;
- (void)clearOptionalStringPiece;
- (BOOL)hasOptionalStringPiece;

@property (nonatomic, strong) NSString *optionalCord;
- (void)clearOptionalCord;
- (BOOL)hasOptionalCord;

@property (nonatomic, strong) PBAppendableArray *repeatedInt32;

@property (nonatomic, strong) PBAppendableArray *repeatedInt64;

@property (nonatomic, strong) PBAppendableArray *repeatedUint32;

@property (nonatomic, strong) PBAppendableArray *repeatedUint64;

@property (nonatomic, strong) PBAppendableArray *repeatedSint32;

@property (nonatomic, strong) PBAppendableArray *repeatedSint64;

@property (nonatomic, strong) PBAppendableArray *repeatedFixed32;

@property (nonatomic, strong) PBAppendableArray *repeatedFixed64;

@property (nonatomic, strong) PBAppendableArray *repeatedSfixed32;

@property (nonatomic, strong) PBAppendableArray *repeatedSfixed64;

@property (nonatomic, strong) PBAppendableArray *repeatedFloat;

@property (nonatomic, strong) PBAppendableArray *repeatedDouble;

@property (nonatomic, strong) PBAppendableArray *repeatedBool;

@property (nonatomic, strong) NSMutableArray *repeatedString;

@property (nonatomic, strong) NSMutableArray *repeatedBytes;

@property (nonatomic, strong) NSMutableArray *repeatedGroup;
@property (nonatomic, strong) NSMutableArray *repeatedNestedMessage;
@property (nonatomic, strong) NSMutableArray *repeatedForeignMessage;
@property (nonatomic, strong) NSMutableArray *repeatedImportMessage;
@property (nonatomic, strong) PBAppendableArray *repeatedNestedEnum;

@property (nonatomic, strong) PBAppendableArray *repeatedForeignEnum;

@property (nonatomic, strong) PBAppendableArray *repeatedImportEnum;

@property (nonatomic, strong) NSMutableArray *repeatedStringPiece;

@property (nonatomic, strong) NSMutableArray *repeatedCord;

@property (nonatomic) int32_t defaultInt32;
- (void)clearDefaultInt32;
- (BOOL)hasDefaultInt32;

@property (nonatomic) int64_t defaultInt64;
- (void)clearDefaultInt64;
- (BOOL)hasDefaultInt64;

@property (nonatomic) uint32_t defaultUint32;
- (void)clearDefaultUint32;
- (BOOL)hasDefaultUint32;

@property (nonatomic) uint64_t defaultUint64;
- (void)clearDefaultUint64;
- (BOOL)hasDefaultUint64;

@property (nonatomic) int32_t defaultSint32;
- (void)clearDefaultSint32;
- (BOOL)hasDefaultSint32;

@property (nonatomic) int64_t defaultSint64;
- (void)clearDefaultSint64;
- (BOOL)hasDefaultSint64;

@property (nonatomic) uint32_t defaultFixed32;
- (void)clearDefaultFixed32;
- (BOOL)hasDefaultFixed32;

@property (nonatomic) uint64_t defaultFixed64;
- (void)clearDefaultFixed64;
- (BOOL)hasDefaultFixed64;

@property (nonatomic) int32_t defaultSfixed32;
- (void)clearDefaultSfixed32;
- (BOOL)hasDefaultSfixed32;

@property (nonatomic) int64_t defaultSfixed64;
- (void)clearDefaultSfixed64;
- (BOOL)hasDefaultSfixed64;

@property (nonatomic) Float32 defaultFloat;
- (void)clearDefaultFloat;
- (BOOL)hasDefaultFloat;

@property (nonatomic) Float64 defaultDouble;
- (void)clearDefaultDouble;
- (BOOL)hasDefaultDouble;

@property (nonatomic) BOOL defaultBool;
- (void)clearDefaultBool;
- (BOOL)hasDefaultBool;

@property (nonatomic, strong) NSString *defaultString;
- (void)clearDefaultString;
- (BOOL)hasDefaultString;

@property (nonatomic, strong) NSData *defaultBytes;
- (void)clearDefaultBytes;
- (BOOL)hasDefaultBytes;

@property (nonatomic) TestAllTypesLite_NestedEnum defaultNestedEnum;
- (void)clearDefaultNestedEnum;
- (BOOL)hasDefaultNestedEnum;

@property (nonatomic) ForeignEnumLite defaultForeignEnum;
- (void)clearDefaultForeignEnum;
- (BOOL)hasDefaultForeignEnum;

@property (nonatomic) ImportEnumLite defaultImportEnum;
- (void)clearDefaultImportEnum;
- (BOOL)hasDefaultImportEnum;

@property (nonatomic, strong) NSString *defaultStringPiece;
- (void)clearDefaultStringPiece;
- (BOOL)hasDefaultStringPiece;

@property (nonatomic, strong) NSString *defaultCord;
- (void)clearDefaultCord;
- (BOOL)hasDefaultCord;

- (int32_t)repeatedInt32AtIndex:(NSUInteger)index;
- (void)addRepeatedInt32:(int32_t)value;
- (void)addRepeatedInt32Array:(NSArray *)array;
- (void)setRepeatedInt32Array:(NSArray *)array;
- (void)setRepeatedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearRepeatedInt32;
- (int64_t)repeatedInt64AtIndex:(NSUInteger)index;
- (void)addRepeatedInt64:(int64_t)value;
- (void)addRepeatedInt64Array:(NSArray *)array;
- (void)setRepeatedInt64Array:(NSArray *)array;
- (void)setRepeatedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearRepeatedInt64;
- (uint32_t)repeatedUint32AtIndex:(NSUInteger)index;
- (void)addRepeatedUint32:(uint32_t)value;
- (void)addRepeatedUint32Array:(NSArray *)array;
- (void)setRepeatedUint32Array:(NSArray *)array;
- (void)setRepeatedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (void)clearRepeatedUint32;
- (uint64_t)repeatedUint64AtIndex:(NSUInteger)index;
- (void)addRepeatedUint64:(uint64_t)value;
- (void)addRepeatedUint64Array:(NSArray *)array;
- (void)setRepeatedUint64Array:(NSArray *)array;
- (void)setRepeatedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (void)clearRepeatedUint64;
- (int32_t)repeatedSint32AtIndex:(NSUInteger)index;
- (void)addRepeatedSint32:(int32_t)value;
- (void)addRepeatedSint32Array:(NSArray *)array;
- (void)setRepeatedSint32Array:(NSArray *)array;
- (void)setRepeatedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearRepeatedSint32;
- (int64_t)repeatedSint64AtIndex:(NSUInteger)index;
- (void)addRepeatedSint64:(int64_t)value;
- (void)addRepeatedSint64Array:(NSArray *)array;
- (void)setRepeatedSint64Array:(NSArray *)array;
- (void)setRepeatedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearRepeatedSint64;
- (uint32_t)repeatedFixed32AtIndex:(NSUInteger)index;
- (void)addRepeatedFixed32:(uint32_t)value;
- (void)addRepeatedFixed32Array:(NSArray *)array;
- (void)setRepeatedFixed32Array:(NSArray *)array;
- (void)setRepeatedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (void)clearRepeatedFixed32;
- (uint64_t)repeatedFixed64AtIndex:(NSUInteger)index;
- (void)addRepeatedFixed64:(uint64_t)value;
- (void)addRepeatedFixed64Array:(NSArray *)array;
- (void)setRepeatedFixed64Array:(NSArray *)array;
- (void)setRepeatedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (void)clearRepeatedFixed64;
- (int32_t)repeatedSfixed32AtIndex:(NSUInteger)index;
- (void)addRepeatedSfixed32:(int32_t)value;
- (void)addRepeatedSfixed32Array:(NSArray *)array;
- (void)setRepeatedSfixed32Array:(NSArray *)array;
- (void)setRepeatedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearRepeatedSfixed32;
- (int64_t)repeatedSfixed64AtIndex:(NSUInteger)index;
- (void)addRepeatedSfixed64:(int64_t)value;
- (void)addRepeatedSfixed64Array:(NSArray *)array;
- (void)setRepeatedSfixed64Array:(NSArray *)array;
- (void)setRepeatedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearRepeatedSfixed64;
- (Float32)repeatedFloatAtIndex:(NSUInteger)index;
- (void)addRepeatedFloat:(Float32)value;
- (void)addRepeatedFloatArray:(NSArray *)array;
- (void)setRepeatedFloatArray:(NSArray *)array;
- (void)setRepeatedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (void)clearRepeatedFloat;
- (Float64)repeatedDoubleAtIndex:(NSUInteger)index;
- (void)addRepeatedDouble:(Float64)value;
- (void)addRepeatedDoubleArray:(NSArray *)array;
- (void)setRepeatedDoubleArray:(NSArray *)array;
- (void)setRepeatedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (void)clearRepeatedDouble;
- (BOOL)repeatedBoolAtIndex:(NSUInteger)index;
- (void)addRepeatedBool:(BOOL)value;
- (void)addRepeatedBoolArray:(NSArray *)array;
- (void)setRepeatedBoolArray:(NSArray *)array;
- (void)setRepeatedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (void)clearRepeatedBool;
- (NSString *)repeatedStringAtIndex:(NSUInteger)index;
- (void)addRepeatedString:(NSString *)value;
- (void)addRepeatedStringArray:(NSArray *)array;
- (void)setRepeatedStringArray:(NSArray *)array;
- (void)clearRepeatedString;
- (NSData *)repeatedBytesAtIndex:(NSUInteger)index;
- (void)addRepeatedBytes:(NSData *)value;
- (void)addRepeatedBytesArray:(NSArray *)array;
- (void)setRepeatedBytesArray:(NSArray *)array;
- (void)clearRepeatedBytes;
- (TestAllTypesLite_RepeatedGroup *)repeatedGroupAtIndex:(NSUInteger)index;
- (void)addRepeatedGroup:(TestAllTypesLite_RepeatedGroup *)value;
- (void)addRepeatedGroupArray:(NSArray *)array;
- (void)setRepeatedGroupArray:(NSArray *)array;
- (TestAllTypesLite_NestedMessage *)repeatedNestedMessageAtIndex:(NSUInteger)index;
- (void)addRepeatedNestedMessage:(TestAllTypesLite_NestedMessage *)value;
- (void)addRepeatedNestedMessageArray:(NSArray *)array;
- (void)setRepeatedNestedMessageArray:(NSArray *)array;
- (ForeignMessageLite *)repeatedForeignMessageAtIndex:(NSUInteger)index;
- (void)addRepeatedForeignMessage:(ForeignMessageLite *)value;
- (void)addRepeatedForeignMessageArray:(NSArray *)array;
- (void)setRepeatedForeignMessageArray:(NSArray *)array;
- (ImportMessageLite *)repeatedImportMessageAtIndex:(NSUInteger)index;
- (void)addRepeatedImportMessage:(ImportMessageLite *)value;
- (void)addRepeatedImportMessageArray:(NSArray *)array;
- (void)setRepeatedImportMessageArray:(NSArray *)array;
- (TestAllTypesLite_NestedEnum)repeatedNestedEnumAtIndex:(NSUInteger)index;
- (void)addRepeatedNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (void)addRepeatedNestedEnumArray:(NSArray *)array;
- (void)setRepeatedNestedEnumArray:(NSArray *)array;
- (void)setRepeatedNestedEnumValues:(const TestAllTypesLite_NestedEnum *)values count:(NSUInteger)count;
- (void)clearRepeatedNestedEnum;
- (ForeignEnumLite)repeatedForeignEnumAtIndex:(NSUInteger)index;
- (void)addRepeatedForeignEnum:(ForeignEnumLite)value;
- (void)addRepeatedForeignEnumArray:(NSArray *)array;
- (void)setRepeatedForeignEnumArray:(NSArray *)array;
- (void)setRepeatedForeignEnumValues:(const ForeignEnumLite *)values count:(NSUInteger)count;
- (void)clearRepeatedForeignEnum;
- (ImportEnumLite)repeatedImportEnumAtIndex:(NSUInteger)index;
- (void)addRepeatedImportEnum:(ImportEnumLite)value;
- (void)addRepeatedImportEnumArray:(NSArray *)array;
- (void)setRepeatedImportEnumArray:(NSArray *)array;
- (void)setRepeatedImportEnumValues:(const ImportEnumLite *)values count:(NSUInteger)count;
- (void)clearRepeatedImportEnum;
- (NSString *)repeatedStringPieceAtIndex:(NSUInteger)index;
- (void)addRepeatedStringPiece:(NSString *)value;
- (void)addRepeatedStringPieceArray:(NSArray *)array;
- (void)setRepeatedStringPieceArray:(NSArray *)array;
- (void)clearRepeatedStringPiece;
- (NSString *)repeatedCordAtIndex:(NSUInteger)index;
- (void)addRepeatedCord:(NSString *)value;
- (void)addRepeatedCordArray:(NSArray *)array;
- (void)setRepeatedCordArray:(NSArray *)array;
- (void)clearRepeatedCord;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestAllTypesLite_Builder *)builder;
+ (TestAllTypesLite_Builder *)builder;
+ (TestAllTypesLite_Builder *)builderWithPrototype:(TestAllTypesLite *)prototype;
- (TestAllTypesLite_Builder *)toBuilder;

+ (TestAllTypesLite *)parseFromData:(NSData *)data;
+ (TestAllTypesLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestAllTypesLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestAllTypesLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestAllTypesLite_NestedMessage : PBGeneratedMessage {
@private
  BOOL _hasBb:1;
}

@property (nonatomic) int32_t bb;
- (void)clearBb;
- (BOOL)hasBb;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestAllTypesLite_NestedMessage_Builder *)builder;
+ (TestAllTypesLite_NestedMessage_Builder *)builder;
+ (TestAllTypesLite_NestedMessage_Builder *)builderWithPrototype:(TestAllTypesLite_NestedMessage *)prototype;
- (TestAllTypesLite_NestedMessage_Builder *)toBuilder;

+ (TestAllTypesLite_NestedMessage *)parseFromData:(NSData *)data;
+ (TestAllTypesLite_NestedMessage *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_NestedMessage *)parseFromInputStream:(NSInputStream *)input;
+ (TestAllTypesLite_NestedMessage *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_NestedMessage *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestAllTypesLite_NestedMessage *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestAllTypesLite_NestedMessage_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_NestedMessage_Builder *)clear;
- (TestAllTypesLite_NestedMessage_Builder *)clone;

- (TestAllTypesLite_NestedMessage *)build;
- (TestAllTypesLite_NestedMessage *)buildPartial;

- (TestAllTypesLite_NestedMessage_Builder *)mergeFrom:(TestAllTypesLite_NestedMessage *)other;
- (TestAllTypesLite_NestedMessage_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestAllTypesLite_NestedMessage_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasBb;
- (int32_t)bb;
- (TestAllTypesLite_NestedMessage_Builder *)setBb:(int32_t)value;
- (TestAllTypesLite_NestedMessage_Builder *)clearBb;

@end


@interface TestAllTypesLite_OptionalGroup : PBGeneratedMessage {
@private
  BOOL _hasA:1;
}

@property (nonatomic) int32_t a;
- (void)clearA;
- (BOOL)hasA;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestAllTypesLite_OptionalGroup_Builder *)builder;
+ (TestAllTypesLite_OptionalGroup_Builder *)builder;
+ (TestAllTypesLite_OptionalGroup_Builder *)builderWithPrototype:(TestAllTypesLite_OptionalGroup *)prototype;
- (TestAllTypesLite_OptionalGroup_Builder *)toBuilder;

+ (TestAllTypesLite_OptionalGroup *)parseFromData:(NSData *)data;
+ (TestAllTypesLite_OptionalGroup *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_OptionalGroup *)parseFromInputStream:(NSInputStream *)input;
+ (TestAllTypesLite_OptionalGroup *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_OptionalGroup *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestAllTypesLite_OptionalGroup *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestAllTypesLite_OptionalGroup_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_OptionalGroup_Builder *)clear;
- (TestAllTypesLite_OptionalGroup_Builder *)clone;

- (TestAllTypesLite_OptionalGroup *)build;
- (TestAllTypesLite_OptionalGroup *)buildPartial;

- (TestAllTypesLite_OptionalGroup_Builder *)mergeFrom:(TestAllTypesLite_OptionalGroup *)other;
- (TestAllTypesLite_OptionalGroup_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestAllTypesLite_OptionalGroup_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasA;
- (int32_t)a;
- (TestAllTypesLite_OptionalGroup_Builder *)setA:(int32_t)value;
- (TestAllTypesLite_OptionalGroup_Builder *)clearA;

@end


@interface TestAllTypesLite_RepeatedGroup : PBGeneratedMessage {
@private
  BOOL _hasA:1;
}

@property (nonatomic) int32_t a;
- (void)clearA;
- (BOOL)hasA;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestAllTypesLite_RepeatedGroup_Builder *)builder;
+ (TestAllTypesLite_RepeatedGroup_Builder *)builder;
+ (TestAllTypesLite_RepeatedGroup_Builder *)builderWithPrototype:(TestAllTypesLite_RepeatedGroup *)prototype;
- (TestAllTypesLite_RepeatedGroup_Builder *)toBuilder;

+ (TestAllTypesLite_RepeatedGroup *)parseFromData:(NSData *)data;
+ (TestAllTypesLite_RepeatedGroup *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_RepeatedGroup *)parseFromInputStream:(NSInputStream *)input;
+ (TestAllTypesLite_RepeatedGroup *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllTypesLite_RepeatedGroup *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestAllTypesLite_RepeatedGroup *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestAllTypesLite_RepeatedGroup_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_RepeatedGroup_Builder *)clear;
- (TestAllTypesLite_RepeatedGroup_Builder *)clone;

- (TestAllTypesLite_RepeatedGroup *)build;
- (TestAllTypesLite_RepeatedGroup *)buildPartial;

- (TestAllTypesLite_RepeatedGroup_Builder *)mergeFrom:(TestAllTypesLite_RepeatedGroup *)other;
- (TestAllTypesLite_RepeatedGroup_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestAllTypesLite_RepeatedGroup_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasA;
- (int32_t)a;
- (TestAllTypesLite_RepeatedGroup_Builder *)setA:(int32_t)value;
- (TestAllTypesLite_RepeatedGroup_Builder *)clearA;

@end


@interface TestAllTypesLite_Builder : PBGeneratedMessage_Builder

- (TestAllTypesLite_Builder *)clear;
- (TestAllTypesLite_Builder *)clone;

- (TestAllTypesLite *)build;
- (TestAllTypesLite *)buildPartial;

- (TestAllTypesLite_Builder *)mergeFrom:(TestAllTypesLite *)other;
- (TestAllTypesLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestAllTypesLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasOptionalInt32;
- (int32_t)optionalInt32;
- (TestAllTypesLite_Builder *)setOptionalInt32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearOptionalInt32;

- (BOOL)hasOptionalInt64;
- (int64_t)optionalInt64;
- (TestAllTypesLite_Builder *)setOptionalInt64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearOptionalInt64;

- (BOOL)hasOptionalUint32;
- (uint32_t)optionalUint32;
- (TestAllTypesLite_Builder *)setOptionalUint32:(uint32_t)value;
- (TestAllTypesLite_Builder *)clearOptionalUint32;

- (BOOL)hasOptionalUint64;
- (uint64_t)optionalUint64;
- (TestAllTypesLite_Builder *)setOptionalUint64:(uint64_t)value;
- (TestAllTypesLite_Builder *)clearOptionalUint64;

- (BOOL)hasOptionalSint32;
- (int32_t)optionalSint32;
- (TestAllTypesLite_Builder *)setOptionalSint32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearOptionalSint32;

- (BOOL)hasOptionalSint64;
- (int64_t)optionalSint64;
- (TestAllTypesLite_Builder *)setOptionalSint64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearOptionalSint64;

- (BOOL)hasOptionalFixed32;
- (uint32_t)optionalFixed32;
- (TestAllTypesLite_Builder *)setOptionalFixed32:(uint32_t)value;
- (TestAllTypesLite_Builder *)clearOptionalFixed32;

- (BOOL)hasOptionalFixed64;
- (uint64_t)optionalFixed64;
- (TestAllTypesLite_Builder *)setOptionalFixed64:(uint64_t)value;
- (TestAllTypesLite_Builder *)clearOptionalFixed64;

- (BOOL)hasOptionalSfixed32;
- (int32_t)optionalSfixed32;
- (TestAllTypesLite_Builder *)setOptionalSfixed32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearOptionalSfixed32;

- (BOOL)hasOptionalSfixed64;
- (int64_t)optionalSfixed64;
- (TestAllTypesLite_Builder *)setOptionalSfixed64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearOptionalSfixed64;

- (BOOL)hasOptionalFloat;
- (Float32)optionalFloat;
- (TestAllTypesLite_Builder *)setOptionalFloat:(Float32)value;
- (TestAllTypesLite_Builder *)clearOptionalFloat;

- (BOOL)hasOptionalDouble;
- (Float64)optionalDouble;
- (TestAllTypesLite_Builder *)setOptionalDouble:(Float64)value;
- (TestAllTypesLite_Builder *)clearOptionalDouble;

- (BOOL)hasOptionalBool;
- (BOOL)optionalBool;
- (TestAllTypesLite_Builder *)setOptionalBool:(BOOL)value;
- (TestAllTypesLite_Builder *)clearOptionalBool;

- (BOOL)hasOptionalString;
- (NSString *)optionalString;
- (TestAllTypesLite_Builder *)setOptionalString:(NSString *)value;
- (TestAllTypesLite_Builder *)clearOptionalString;

- (BOOL)hasOptionalBytes;
- (NSData *)optionalBytes;
- (TestAllTypesLite_Builder *)setOptionalBytes:(NSData *)value;
- (TestAllTypesLite_Builder *)clearOptionalBytes;

- (BOOL)hasOptionalGroup;
- (TestAllTypesLite_OptionalGroup *)optionalGroup;
- (TestAllTypesLite_Builder *)setOptionalGroup:(TestAllTypesLite_OptionalGroup *)value;
- (TestAllTypesLite_Builder *)setOptionalGroupBuilder:(TestAllTypesLite_OptionalGroup_Builder *)builderForValue;
- (TestAllTypesLite_Builder *)mergeOptionalGroup:(TestAllTypesLite_OptionalGroup *)value;
- (TestAllTypesLite_Builder *)clearOptionalGroup;

- (BOOL)hasOptionalNestedMessage;
- (TestAllTypesLite_NestedMessage *)optionalNestedMessage;
- (TestAllTypesLite_Builder *)setOptionalNestedMessage:(TestAllTypesLite_NestedMessage *)value;
- (TestAllTypesLite_Builder *)setOptionalNestedMessageBuilder:(TestAllTypesLite_NestedMessage_Builder *)builderForValue;
- (TestAllTypesLite_Builder *)mergeOptionalNestedMessage:(TestAllTypesLite_NestedMessage *)value;
- (TestAllTypesLite_Builder *)clearOptionalNestedMessage;

- (BOOL)hasOptionalForeignMessage;
- (ForeignMessageLite *)optionalForeignMessage;
- (TestAllTypesLite_Builder *)setOptionalForeignMessage:(ForeignMessageLite *)value;
- (TestAllTypesLite_Builder *)setOptionalForeignMessageBuilder:(ForeignMessageLite_Builder *)builderForValue;
- (TestAllTypesLite_Builder *)mergeOptionalForeignMessage:(ForeignMessageLite *)value;
- (TestAllTypesLite_Builder *)clearOptionalForeignMessage;

- (BOOL)hasOptionalImportMessage;
- (ImportMessageLite *)optionalImportMessage;
- (TestAllTypesLite_Builder *)setOptionalImportMessage:(ImportMessageLite *)value;
- (TestAllTypesLite_Builder *)setOptionalImportMessageBuilder:(ImportMessageLite_Builder *)builderForValue;
- (TestAllTypesLite_Builder *)mergeOptionalImportMessage:(ImportMessageLite *)value;
- (TestAllTypesLite_Builder *)clearOptionalImportMessage;

- (BOOL)hasOptionalNestedEnum;
- (TestAllTypesLite_NestedEnum)optionalNestedEnum;
- (TestAllTypesLite_Builder *)setOptionalNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (TestAllTypesLite_Builder *)clearOptionalNestedEnum;

- (BOOL)hasOptionalForeignEnum;
- (ForeignEnumLite)optionalForeignEnum;
- (TestAllTypesLite_Builder *)setOptionalForeignEnum:(ForeignEnumLite)value;
- (TestAllTypesLite_Builder *)clearOptionalForeignEnum;

- (BOOL)hasOptionalImportEnum;
- (ImportEnumLite)optionalImportEnum;
- (TestAllTypesLite_Builder *)setOptionalImportEnum:(ImportEnumLite)value;
- (TestAllTypesLite_Builder *)clearOptionalImportEnum;

- (BOOL)hasOptionalStringPiece;
- (NSString *)optionalStringPiece;
- (TestAllTypesLite_Builder *)setOptionalStringPiece:(NSString *)value;
- (TestAllTypesLite_Builder *)clearOptionalStringPiece;

- (BOOL)hasOptionalCord;
- (NSString *)optionalCord;
- (TestAllTypesLite_Builder *)setOptionalCord:(NSString *)value;
- (TestAllTypesLite_Builder *)clearOptionalCord;

- (NSMutableArray *)repeatedInt32;
- (int32_t)repeatedInt32AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedInt32:(int32_t)value;
- (TestAllTypesLite_Builder *)setRepeatedInt32Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedInt32;

- (NSMutableArray *)repeatedInt64;
- (int64_t)repeatedInt64AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedInt64:(int64_t)value;
- (TestAllTypesLite_Builder *)setRepeatedInt64Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedInt64;

- (NSMutableArray *)repeatedUint32;
- (uint32_t)repeatedUint32AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedUint32:(uint32_t)value;
- (TestAllTypesLite_Builder *)setRepeatedUint32Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedUint32;

- (NSMutableArray *)repeatedUint64;
- (uint64_t)repeatedUint64AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedUint64:(uint64_t)value;
- (TestAllTypesLite_Builder *)setRepeatedUint64Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedUint64;

- (NSMutableArray *)repeatedSint32;
- (int32_t)repeatedSint32AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedSint32:(int32_t)value;
- (TestAllTypesLite_Builder *)setRepeatedSint32Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedSint32;

- (NSMutableArray *)repeatedSint64;
- (int64_t)repeatedSint64AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedSint64:(int64_t)value;
- (TestAllTypesLite_Builder *)setRepeatedSint64Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedSint64;

- (NSMutableArray *)repeatedFixed32;
- (uint32_t)repeatedFixed32AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedFixed32:(uint32_t)value;
- (TestAllTypesLite_Builder *)setRepeatedFixed32Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedFixed32;

- (NSMutableArray *)repeatedFixed64;
- (uint64_t)repeatedFixed64AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedFixed64:(uint64_t)value;
- (TestAllTypesLite_Builder *)setRepeatedFixed64Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedFixed64;

- (NSMutableArray *)repeatedSfixed32;
- (int32_t)repeatedSfixed32AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedSfixed32:(int32_t)value;
- (TestAllTypesLite_Builder *)setRepeatedSfixed32Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedSfixed32;

- (NSMutableArray *)repeatedSfixed64;
- (int64_t)repeatedSfixed64AtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedSfixed64:(int64_t)value;
- (TestAllTypesLite_Builder *)setRepeatedSfixed64Array:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedSfixed64;

- (NSMutableArray *)repeatedFloat;
- (Float32)repeatedFloatAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedFloat:(Float32)value;
- (TestAllTypesLite_Builder *)setRepeatedFloatArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedFloat;

- (NSMutableArray *)repeatedDouble;
- (Float64)repeatedDoubleAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedDouble:(Float64)value;
- (TestAllTypesLite_Builder *)setRepeatedDoubleArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedDouble;

- (NSMutableArray *)repeatedBool;
- (BOOL)repeatedBoolAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedBool:(BOOL)value;
- (TestAllTypesLite_Builder *)setRepeatedBoolArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedBool;

- (NSMutableArray *)repeatedString;
- (NSString *)repeatedStringAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedString:(NSString *)value;
- (TestAllTypesLite_Builder *)setRepeatedStringArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedString;

- (NSMutableArray *)repeatedBytes;
- (NSData *)repeatedBytesAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedBytes:(NSData *)value;
- (TestAllTypesLite_Builder *)setRepeatedBytesArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedBytes;

- (NSMutableArray *)repeatedGroup;
- (TestAllTypesLite_RepeatedGroup *)repeatedGroupAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedGroup:(TestAllTypesLite_RepeatedGroup *)value;
- (TestAllTypesLite_Builder *)setRepeatedGroupArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedGroup;

- (NSMutableArray *)repeatedNestedMessage;
- (TestAllTypesLite_NestedMessage *)repeatedNestedMessageAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedNestedMessage:(TestAllTypesLite_NestedMessage *)value;
- (TestAllTypesLite_Builder *)setRepeatedNestedMessageArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedNestedMessage;

- (NSMutableArray *)repeatedForeignMessage;
- (ForeignMessageLite *)repeatedForeignMessageAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedForeignMessage:(ForeignMessageLite *)value;
- (TestAllTypesLite_Builder *)setRepeatedForeignMessageArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedForeignMessage;

- (NSMutableArray *)repeatedImportMessage;
- (ImportMessageLite *)repeatedImportMessageAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedImportMessage:(ImportMessageLite *)value;
- (TestAllTypesLite_Builder *)setRepeatedImportMessageArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedImportMessage;

- (PBAppendableArray *)repeatedNestedEnum;
- (TestAllTypesLite_NestedEnum)repeatedNestedEnumAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (TestAllTypesLite_Builder *)setRepeatedNestedEnumArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedNestedEnumValues:(const TestAllTypesLite_NestedEnum *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedNestedEnum;

- (PBAppendableArray *)repeatedForeignEnum;
- (ForeignEnumLite)repeatedForeignEnumAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedForeignEnum:(ForeignEnumLite)value;
- (TestAllTypesLite_Builder *)setRepeatedForeignEnumArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedForeignEnumValues:(const ForeignEnumLite *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedForeignEnum;

- (PBAppendableArray *)repeatedImportEnum;
- (ImportEnumLite)repeatedImportEnumAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedImportEnum:(ImportEnumLite)value;
- (TestAllTypesLite_Builder *)setRepeatedImportEnumArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)setRepeatedImportEnumValues:(const ImportEnumLite *)values count:(NSUInteger)count;
- (TestAllTypesLite_Builder *)clearRepeatedImportEnum;

- (NSMutableArray *)repeatedStringPiece;
- (NSString *)repeatedStringPieceAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedStringPiece:(NSString *)value;
- (TestAllTypesLite_Builder *)setRepeatedStringPieceArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedStringPiece;

- (NSMutableArray *)repeatedCord;
- (NSString *)repeatedCordAtIndex:(NSUInteger)index;
- (TestAllTypesLite_Builder *)addRepeatedCord:(NSString *)value;
- (TestAllTypesLite_Builder *)setRepeatedCordArray:(NSArray *)array;
- (TestAllTypesLite_Builder *)clearRepeatedCord;

- (BOOL)hasDefaultInt32;
- (int32_t)defaultInt32;
- (TestAllTypesLite_Builder *)setDefaultInt32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearDefaultInt32;

- (BOOL)hasDefaultInt64;
- (int64_t)defaultInt64;
- (TestAllTypesLite_Builder *)setDefaultInt64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearDefaultInt64;

- (BOOL)hasDefaultUint32;
- (uint32_t)defaultUint32;
- (TestAllTypesLite_Builder *)setDefaultUint32:(uint32_t)value;
- (TestAllTypesLite_Builder *)clearDefaultUint32;

- (BOOL)hasDefaultUint64;
- (uint64_t)defaultUint64;
- (TestAllTypesLite_Builder *)setDefaultUint64:(uint64_t)value;
- (TestAllTypesLite_Builder *)clearDefaultUint64;

- (BOOL)hasDefaultSint32;
- (int32_t)defaultSint32;
- (TestAllTypesLite_Builder *)setDefaultSint32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearDefaultSint32;

- (BOOL)hasDefaultSint64;
- (int64_t)defaultSint64;
- (TestAllTypesLite_Builder *)setDefaultSint64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearDefaultSint64;

- (BOOL)hasDefaultFixed32;
- (uint32_t)defaultFixed32;
- (TestAllTypesLite_Builder *)setDefaultFixed32:(uint32_t)value;
- (TestAllTypesLite_Builder *)clearDefaultFixed32;

- (BOOL)hasDefaultFixed64;
- (uint64_t)defaultFixed64;
- (TestAllTypesLite_Builder *)setDefaultFixed64:(uint64_t)value;
- (TestAllTypesLite_Builder *)clearDefaultFixed64;

- (BOOL)hasDefaultSfixed32;
- (int32_t)defaultSfixed32;
- (TestAllTypesLite_Builder *)setDefaultSfixed32:(int32_t)value;
- (TestAllTypesLite_Builder *)clearDefaultSfixed32;

- (BOOL)hasDefaultSfixed64;
- (int64_t)defaultSfixed64;
- (TestAllTypesLite_Builder *)setDefaultSfixed64:(int64_t)value;
- (TestAllTypesLite_Builder *)clearDefaultSfixed64;

- (BOOL)hasDefaultFloat;
- (Float32)defaultFloat;
- (TestAllTypesLite_Builder *)setDefaultFloat:(Float32)value;
- (TestAllTypesLite_Builder *)clearDefaultFloat;

- (BOOL)hasDefaultDouble;
- (Float64)defaultDouble;
- (TestAllTypesLite_Builder *)setDefaultDouble:(Float64)value;
- (TestAllTypesLite_Builder *)clearDefaultDouble;

- (BOOL)hasDefaultBool;
- (BOOL)defaultBool;
- (TestAllTypesLite_Builder *)setDefaultBool:(BOOL)value;
- (TestAllTypesLite_Builder *)clearDefaultBool;

- (BOOL)hasDefaultString;
- (NSString *)defaultString;
- (TestAllTypesLite_Builder *)setDefaultString:(NSString *)value;
- (TestAllTypesLite_Builder *)clearDefaultString;

- (BOOL)hasDefaultBytes;
- (NSData *)defaultBytes;
- (TestAllTypesLite_Builder *)setDefaultBytes:(NSData *)value;
- (TestAllTypesLite_Builder *)clearDefaultBytes;

- (BOOL)hasDefaultNestedEnum;
- (TestAllTypesLite_NestedEnum)defaultNestedEnum;
- (TestAllTypesLite_Builder *)setDefaultNestedEnum:(TestAllTypesLite_NestedEnum)value;
- (TestAllTypesLite_Builder *)clearDefaultNestedEnum;

- (BOOL)hasDefaultForeignEnum;
- (ForeignEnumLite)defaultForeignEnum;
- (TestAllTypesLite_Builder *)setDefaultForeignEnum:(ForeignEnumLite)value;
- (TestAllTypesLite_Builder *)clearDefaultForeignEnum;

- (BOOL)hasDefaultImportEnum;
- (ImportEnumLite)defaultImportEnum;
- (TestAllTypesLite_Builder *)setDefaultImportEnum:(ImportEnumLite)value;
- (TestAllTypesLite_Builder *)clearDefaultImportEnum;

- (BOOL)hasDefaultStringPiece;
- (NSString *)defaultStringPiece;
- (TestAllTypesLite_Builder *)setDefaultStringPiece:(NSString *)value;
- (TestAllTypesLite_Builder *)clearDefaultStringPiece;

- (BOOL)hasDefaultCord;
- (NSString *)defaultCord;
- (TestAllTypesLite_Builder *)setDefaultCord:(NSString *)value;
- (TestAllTypesLite_Builder *)clearDefaultCord;

@end


@interface ForeignMessageLite : PBGeneratedMessage {
@private
  BOOL _hasC:1;
}

@property (nonatomic) int32_t c;
- (void)clearC;
- (BOOL)hasC;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (ForeignMessageLite_Builder *)builder;
+ (ForeignMessageLite_Builder *)builder;
+ (ForeignMessageLite_Builder *)builderWithPrototype:(ForeignMessageLite *)prototype;
- (ForeignMessageLite_Builder *)toBuilder;

+ (ForeignMessageLite *)parseFromData:(NSData *)data;
+ (ForeignMessageLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (ForeignMessageLite *)parseFromInputStream:(NSInputStream *)input;
+ (ForeignMessageLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (ForeignMessageLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (ForeignMessageLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface ForeignMessageLite_Builder : PBGeneratedMessage_Builder

- (ForeignMessageLite_Builder *)clear;
- (ForeignMessageLite_Builder *)clone;

- (ForeignMessageLite *)build;
- (ForeignMessageLite *)buildPartial;

- (ForeignMessageLite_Builder *)mergeFrom:(ForeignMessageLite *)other;
- (ForeignMessageLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (ForeignMessageLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasC;
- (int32_t)c;
- (ForeignMessageLite_Builder *)setC:(int32_t)value;
- (ForeignMessageLite_Builder *)clearC;

@end


@interface TestPackedTypesLite : PBGeneratedMessage {
@private
  int32_t _packedBoolMemoizedSerializedSize;
  int32_t _packedDoubleMemoizedSerializedSize;
  int32_t _packedFloatMemoizedSerializedSize;
  int32_t _packedInt64MemoizedSerializedSize;
  int32_t _packedUint64MemoizedSerializedSize;
  int32_t _packedInt32MemoizedSerializedSize;
  int32_t _packedFixed64MemoizedSerializedSize;
  int32_t _packedFixed32MemoizedSerializedSize;
  int32_t _packedUint32MemoizedSerializedSize;
  int32_t _packedEnumMemoizedSerializedSize;
  int32_t _packedSfixed32MemoizedSerializedSize;
  int32_t _packedSfixed64MemoizedSerializedSize;
  int32_t _packedSint32MemoizedSerializedSize;
  int32_t _packedSint64MemoizedSerializedSize;
}

@property (nonatomic, strong) PBAppendableArray *packedInt32;

@property (nonatomic, strong) PBAppendableArray *packedInt64;

@property (nonatomic, strong) PBAppendableArray *packedUint32;

@property (nonatomic, strong) PBAppendableArray *packedUint64;

@property (nonatomic, strong) PBAppendableArray *packedSint32;

@property (nonatomic, strong) PBAppendableArray *packedSint64;

@property (nonatomic, strong) PBAppendableArray *packedFixed32;

@property (nonatomic, strong) PBAppendableArray *packedFixed64;

@property (nonatomic, strong) PBAppendableArray *packedSfixed32;

@property (nonatomic, strong) PBAppendableArray *packedSfixed64;

@property (nonatomic, strong) PBAppendableArray *packedFloat;

@property (nonatomic, strong) PBAppendableArray *packedDouble;

@property (nonatomic, strong) PBAppendableArray *packedBool;

@property (nonatomic, strong) PBAppendableArray *packedEnum;

- (int32_t)packedInt32AtIndex:(NSUInteger)index;
- (void)addPackedInt32:(int32_t)value;
- (void)addPackedInt32Array:(NSArray *)array;
- (void)setPackedInt32Array:(NSArray *)array;
- (void)setPackedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearPackedInt32;
- (int64_t)packedInt64AtIndex:(NSUInteger)index;
- (void)addPackedInt64:(int64_t)value;
- (void)addPackedInt64Array:(NSArray *)array;
- (void)setPackedInt64Array:(NSArray *)array;
- (void)setPackedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearPackedInt64;
- (uint32_t)packedUint32AtIndex:(NSUInteger)index;
- (void)addPackedUint32:(uint32_t)value;
- (void)addPackedUint32Array:(NSArray *)array;
- (void)setPackedUint32Array:(NSArray *)array;
- (void)setPackedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (void)clearPackedUint32;
- (uint64_t)packedUint64AtIndex:(NSUInteger)index;
- (void)addPackedUint64:(uint64_t)value;
- (void)addPackedUint64Array:(NSArray *)array;
- (void)setPackedUint64Array:(NSArray *)array;
- (void)setPackedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (void)clearPackedUint64;
- (int32_t)packedSint32AtIndex:(NSUInteger)index;
- (void)addPackedSint32:(int32_t)value;
- (void)addPackedSint32Array:(NSArray *)array;
- (void)setPackedSint32Array:(NSArray *)array;
- (void)setPackedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearPackedSint32;
- (int64_t)packedSint64AtIndex:(NSUInteger)index;
- (void)addPackedSint64:(int64_t)value;
- (void)addPackedSint64Array:(NSArray *)array;
- (void)setPackedSint64Array:(NSArray *)array;
- (void)setPackedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearPackedSint64;
- (uint32_t)packedFixed32AtIndex:(NSUInteger)index;
- (void)addPackedFixed32:(uint32_t)value;
- (void)addPackedFixed32Array:(NSArray *)array;
- (void)setPackedFixed32Array:(NSArray *)array;
- (void)setPackedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (void)clearPackedFixed32;
- (uint64_t)packedFixed64AtIndex:(NSUInteger)index;
- (void)addPackedFixed64:(uint64_t)value;
- (void)addPackedFixed64Array:(NSArray *)array;
- (void)setPackedFixed64Array:(NSArray *)array;
- (void)setPackedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (void)clearPackedFixed64;
- (int32_t)packedSfixed32AtIndex:(NSUInteger)index;
- (void)addPackedSfixed32:(int32_t)value;
- (void)addPackedSfixed32Array:(NSArray *)array;
- (void)setPackedSfixed32Array:(NSArray *)array;
- (void)setPackedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (void)clearPackedSfixed32;
- (int64_t)packedSfixed64AtIndex:(NSUInteger)index;
- (void)addPackedSfixed64:(int64_t)value;
- (void)addPackedSfixed64Array:(NSArray *)array;
- (void)setPackedSfixed64Array:(NSArray *)array;
- (void)setPackedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (void)clearPackedSfixed64;
- (Float32)packedFloatAtIndex:(NSUInteger)index;
- (void)addPackedFloat:(Float32)value;
- (void)addPackedFloatArray:(NSArray *)array;
- (void)setPackedFloatArray:(NSArray *)array;
- (void)setPackedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (void)clearPackedFloat;
- (Float64)packedDoubleAtIndex:(NSUInteger)index;
- (void)addPackedDouble:(Float64)value;
- (void)addPackedDoubleArray:(NSArray *)array;
- (void)setPackedDoubleArray:(NSArray *)array;
- (void)setPackedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (void)clearPackedDouble;
- (BOOL)packedBoolAtIndex:(NSUInteger)index;
- (void)addPackedBool:(BOOL)value;
- (void)addPackedBoolArray:(NSArray *)array;
- (void)setPackedBoolArray:(NSArray *)array;
- (void)setPackedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (void)clearPackedBool;
- (ForeignEnumLite)packedEnumAtIndex:(NSUInteger)index;
- (void)addPackedEnum:(ForeignEnumLite)value;
- (void)addPackedEnumArray:(NSArray *)array;
- (void)setPackedEnumArray:(NSArray *)array;
- (void)setPackedEnumValues:(const ForeignEnumLite *)values count:(NSUInteger)count;
- (void)clearPackedEnum;

- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestPackedTypesLite_Builder *)builder;
+ (TestPackedTypesLite_Builder *)builder;
+ (TestPackedTypesLite_Builder *)builderWithPrototype:(TestPackedTypesLite *)prototype;
- (TestPackedTypesLite_Builder *)toBuilder;

+ (TestPackedTypesLite *)parseFromData:(NSData *)data;
+ (TestPackedTypesLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestPackedTypesLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestPackedTypesLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestPackedTypesLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestPackedTypesLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestPackedTypesLite_Builder : PBGeneratedMessage_Builder

- (TestPackedTypesLite_Builder *)clear;
- (TestPackedTypesLite_Builder *)clone;

- (TestPackedTypesLite *)build;
- (TestPackedTypesLite *)buildPartial;

- (TestPackedTypesLite_Builder *)mergeFrom:(TestPackedTypesLite *)other;
- (TestPackedTypesLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestPackedTypesLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (NSMutableArray *)packedInt32;
- (int32_t)packedInt32AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedInt32:(int32_t)value;
- (TestPackedTypesLite_Builder *)setPackedInt32Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedInt32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedInt32;

- (NSMutableArray *)packedInt64;
- (int64_t)packedInt64AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedInt64:(int64_t)value;
- (TestPackedTypesLite_Builder *)setPackedInt64Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedInt64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedInt64;

- (NSMutableArray *)packedUint32;
- (uint32_t)packedUint32AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedUint32:(uint32_t)value;
- (TestPackedTypesLite_Builder *)setPackedUint32Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedUint32Values:(const uint32_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedUint32;

- (NSMutableArray *)packedUint64;
- (uint64_t)packedUint64AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedUint64:(uint64_t)value;
- (TestPackedTypesLite_Builder *)setPackedUint64Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedUint64Values:(const uint64_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedUint64;

- (NSMutableArray *)packedSint32;
- (int32_t)packedSint32AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedSint32:(int32_t)value;
- (TestPackedTypesLite_Builder *)setPackedSint32Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedSint32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedSint32;

- (NSMutableArray *)packedSint64;
- (int64_t)packedSint64AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedSint64:(int64_t)value;
- (TestPackedTypesLite_Builder *)setPackedSint64Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedSint64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedSint64;

- (NSMutableArray *)packedFixed32;
- (uint32_t)packedFixed32AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedFixed32:(uint32_t)value;
- (TestPackedTypesLite_Builder *)setPackedFixed32Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedFixed32Values:(const uint32_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedFixed32;

- (NSMutableArray *)packedFixed64;
- (uint64_t)packedFixed64AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedFixed64:(uint64_t)value;
- (TestPackedTypesLite_Builder *)setPackedFixed64Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedFixed64Values:(const uint64_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedFixed64;

- (NSMutableArray *)packedSfixed32;
- (int32_t)packedSfixed32AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedSfixed32:(int32_t)value;
- (TestPackedTypesLite_Builder *)setPackedSfixed32Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedSfixed32Values:(const int32_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedSfixed32;

- (NSMutableArray *)packedSfixed64;
- (int64_t)packedSfixed64AtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedSfixed64:(int64_t)value;
- (TestPackedTypesLite_Builder *)setPackedSfixed64Array:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedSfixed64Values:(const int64_t *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedSfixed64;

- (NSMutableArray *)packedFloat;
- (Float32)packedFloatAtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedFloat:(Float32)value;
- (TestPackedTypesLite_Builder *)setPackedFloatArray:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedFloatValues:(const Float32 *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedFloat;

- (NSMutableArray *)packedDouble;
- (Float64)packedDoubleAtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedDouble:(Float64)value;
- (TestPackedTypesLite_Builder *)setPackedDoubleArray:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedDoubleValues:(const Float64 *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedDouble;

- (NSMutableArray *)packedBool;
- (BOOL)packedBoolAtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedBool:(BOOL)value;
- (TestPackedTypesLite_Builder *)setPackedBoolArray:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedBoolValues:(const BOOL *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedBool;

- (PBAppendableArray *)packedEnum;
- (ForeignEnumLite)packedEnumAtIndex:(NSUInteger)index;
- (TestPackedTypesLite_Builder *)addPackedEnum:(ForeignEnumLite)value;
- (TestPackedTypesLite_Builder *)setPackedEnumArray:(NSArray *)array;
- (TestPackedTypesLite_Builder *)setPackedEnumValues:(const ForeignEnumLite *)values count:(NSUInteger)count;
- (TestPackedTypesLite_Builder *)clearPackedEnum;

@end


@interface TestAllExtensionsLite : PBExtendableMessage {
@private
}


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestAllExtensionsLite_Builder *)builder;
+ (TestAllExtensionsLite_Builder *)builder;
+ (TestAllExtensionsLite_Builder *)builderWithPrototype:(TestAllExtensionsLite *)prototype;
- (TestAllExtensionsLite_Builder *)toBuilder;

+ (TestAllExtensionsLite *)parseFromData:(NSData *)data;
+ (TestAllExtensionsLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllExtensionsLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestAllExtensionsLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestAllExtensionsLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestAllExtensionsLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestAllExtensionsLite_Builder : PBExtendableMessage_Builder

- (TestAllExtensionsLite_Builder *)clear;
- (TestAllExtensionsLite_Builder *)clone;

- (TestAllExtensionsLite *)build;
- (TestAllExtensionsLite *)buildPartial;

- (TestAllExtensionsLite_Builder *)mergeFrom:(TestAllExtensionsLite *)other;
- (TestAllExtensionsLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestAllExtensionsLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface OptionalGroup_extension_lite : PBGeneratedMessage {
@private
  BOOL _hasA:1;
}

@property (nonatomic) int32_t a;
- (void)clearA;
- (BOOL)hasA;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (OptionalGroup_extension_lite_Builder *)builder;
+ (OptionalGroup_extension_lite_Builder *)builder;
+ (OptionalGroup_extension_lite_Builder *)builderWithPrototype:(OptionalGroup_extension_lite *)prototype;
- (OptionalGroup_extension_lite_Builder *)toBuilder;

+ (OptionalGroup_extension_lite *)parseFromData:(NSData *)data;
+ (OptionalGroup_extension_lite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (OptionalGroup_extension_lite *)parseFromInputStream:(NSInputStream *)input;
+ (OptionalGroup_extension_lite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (OptionalGroup_extension_lite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (OptionalGroup_extension_lite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface OptionalGroup_extension_lite_Builder : PBGeneratedMessage_Builder

- (OptionalGroup_extension_lite_Builder *)clear;
- (OptionalGroup_extension_lite_Builder *)clone;

- (OptionalGroup_extension_lite *)build;
- (OptionalGroup_extension_lite *)buildPartial;

- (OptionalGroup_extension_lite_Builder *)mergeFrom:(OptionalGroup_extension_lite *)other;
- (OptionalGroup_extension_lite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (OptionalGroup_extension_lite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasA;
- (int32_t)a;
- (OptionalGroup_extension_lite_Builder *)setA:(int32_t)value;
- (OptionalGroup_extension_lite_Builder *)clearA;

@end


@interface RepeatedGroup_extension_lite : PBGeneratedMessage {
@private
  BOOL _hasA:1;
}

@property (nonatomic) int32_t a;
- (void)clearA;
- (BOOL)hasA;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (RepeatedGroup_extension_lite_Builder *)builder;
+ (RepeatedGroup_extension_lite_Builder *)builder;
+ (RepeatedGroup_extension_lite_Builder *)builderWithPrototype:(RepeatedGroup_extension_lite *)prototype;
- (RepeatedGroup_extension_lite_Builder *)toBuilder;

+ (RepeatedGroup_extension_lite *)parseFromData:(NSData *)data;
+ (RepeatedGroup_extension_lite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (RepeatedGroup_extension_lite *)parseFromInputStream:(NSInputStream *)input;
+ (RepeatedGroup_extension_lite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (RepeatedGroup_extension_lite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (RepeatedGroup_extension_lite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface RepeatedGroup_extension_lite_Builder : PBGeneratedMessage_Builder

- (RepeatedGroup_extension_lite_Builder *)clear;
- (RepeatedGroup_extension_lite_Builder *)clone;

- (RepeatedGroup_extension_lite *)build;
- (RepeatedGroup_extension_lite *)buildPartial;

- (RepeatedGroup_extension_lite_Builder *)mergeFrom:(RepeatedGroup_extension_lite *)other;
- (RepeatedGroup_extension_lite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (RepeatedGroup_extension_lite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasA;
- (int32_t)a;
- (RepeatedGroup_extension_lite_Builder *)setA:(int32_t)value;
- (RepeatedGroup_extension_lite_Builder *)clearA;

@end


@interface TestPackedExtensionsLite : PBExtendableMessage {
@private
}


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestPackedExtensionsLite_Builder *)builder;
+ (TestPackedExtensionsLite_Builder *)builder;
+ (TestPackedExtensionsLite_Builder *)builderWithPrototype:(TestPackedExtensionsLite *)prototype;
- (TestPackedExtensionsLite_Builder *)toBuilder;

+ (TestPackedExtensionsLite *)parseFromData:(NSData *)data;
+ (TestPackedExtensionsLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestPackedExtensionsLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestPackedExtensionsLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestPackedExtensionsLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestPackedExtensionsLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestPackedExtensionsLite_Builder : PBExtendableMessage_Builder

- (TestPackedExtensionsLite_Builder *)clear;
- (TestPackedExtensionsLite_Builder *)clone;

- (TestPackedExtensionsLite *)build;
- (TestPackedExtensionsLite *)buildPartial;

- (TestPackedExtensionsLite_Builder *)mergeFrom:(TestPackedExtensionsLite *)other;
- (TestPackedExtensionsLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestPackedExtensionsLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestNestedExtensionLite : PBGeneratedMessage {
@private
}


+ (id<PBExtensionField>)nestedExtension;
- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestNestedExtensionLite_Builder *)builder;
+ (TestNestedExtensionLite_Builder *)builder;
+ (TestNestedExtensionLite_Builder *)builderWithPrototype:(TestNestedExtensionLite *)prototype;
- (TestNestedExtensionLite_Builder *)toBuilder;

+ (TestNestedExtensionLite *)parseFromData:(NSData *)data;
+ (TestNestedExtensionLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestNestedExtensionLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestNestedExtensionLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestNestedExtensionLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestNestedExtensionLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestNestedExtensionLite_Builder : PBGeneratedMessage_Builder

- (TestNestedExtensionLite_Builder *)clear;
- (TestNestedExtensionLite_Builder *)clone;

- (TestNestedExtensionLite *)build;
- (TestNestedExtensionLite *)buildPartial;

- (TestNestedExtensionLite_Builder *)mergeFrom:(TestNestedExtensionLite *)other;
- (TestNestedExtensionLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestNestedExtensionLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestDeprecatedLite : PBGeneratedMessage {
@private
  BOOL _hasDeprecatedField:1;
}

@property (nonatomic) int32_t deprecatedField;
- (void)clearDeprecatedField;
- (BOOL)hasDeprecatedField;


- (BOOL)isInitialized;
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output;

- (TestDeprecatedLite_Builder *)builder;
+ (TestDeprecatedLite_Builder *)builder;
+ (TestDeprecatedLite_Builder *)builderWithPrototype:(TestDeprecatedLite *)prototype;
- (TestDeprecatedLite_Builder *)toBuilder;

+ (TestDeprecatedLite *)parseFromData:(NSData *)data;
+ (TestDeprecatedLite *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestDeprecatedLite *)parseFromInputStream:(NSInputStream *)input;
+ (TestDeprecatedLite *)parseFromInputStream:(NSInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;
+ (TestDeprecatedLite *)parseFromCodedInputStream:(PBCodedInputStream *)input;
+ (TestDeprecatedLite *)parseFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

@end


@interface TestDeprecatedLite_Builder : PBGeneratedMessage_Builder

- (TestDeprecatedLite_Builder *)clear;
- (TestDeprecatedLite_Builder *)clone;

- (TestDeprecatedLite *)build;
- (TestDeprecatedLite *)buildPartial;

- (TestDeprecatedLite_Builder *)mergeFrom:(TestDeprecatedLite *)other;
- (TestDeprecatedLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input;
- (TestDeprecatedLite_Builder *)mergeFromCodedInputStream:(PBCodedInputStream *)input extensionRegistry:(PBExtensionRegistry *)extensionRegistry;

- (BOOL)hasDeprecatedField;
- (int32_t)deprecatedField;
- (TestDeprecatedLite_Builder *)setDeprecatedField:(int32_t)value;
- (TestDeprecatedLite_Builder *)clearDeprecatedField;

@end


